#
# *******************************************************************************
# * Copyright © Temenos Headquarters SA 2021. All rights reserved.
# *******************************************************************************
#

# Default values for dbInitialisation.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  appinit:
    repository: dev.local/temenos/ms-paymentorder-appinit
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: DEV

# Set the pull secret name here
#imagePullSecrets: all-icr-io

restartPolicy: OnFailure

env:
  appinit:
    databaseKey: mongodb
    databaseName: ms_paymentorder
    dbConnectionUrl: mongodb://mongodb-0.mongodb-svc.mongodb.svc.cluster.local:27017,mongodb-1.mongodb-svc.mongodb.svc.cluster.local:27017,mongodb-2.mongodb-svc.mongodb.svc.cluster.local:27017
    dbUserName: 
    dbPassword:
    dbautoupgrade: "N"
    exportType: socket
    socketHost: 
    socketPort: 4560

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

