apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: paymentorder-scheduler
  namespace: paymentorder
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: paymentorder-scheduler
            image: dev.local/temenos/ms-paymentorder-scheduler:DEV
            imagePullPolicy: Never
            env:
              - name: DATABASE_KEY
                value: mongodb
              - name: MONGODB_DBNAME
                value: ms_paymentorder
              - name: MONGODB_CONNECTIONSTR
                value: mongodb://mongodb-0.mongodb-svc.mongodb.svc.cluster.local:27017,mongodb-1.mongodb-svc.mongodb.svc.cluster.local:27017,mongodb-2.mongodb-svc.mongodb.svc.cluster.local:27017
              - name: temn.msf.name
                value: PaymentOrder
              - name: temn.msf.security.authz.enabled
                value: "false"             
              - name: className_paymentscheduler
                value: com.temenos.microservice.paymentorder.scheduler.PaymentOrderScheduler 
              - name: className_nosqlInboxCatchup
                value: com.temenos.microservice.framework.scheduler.core.NoSqlInboxCatchupProcessor
              - name: className_nosqlOutboxCatchup
                value: com.temenos.microservice.framework.scheduler.core.NoSqlOutboxCatchupProcessor          
              - name: operationId
                value: paymentscheduler            
          restartPolicy: OnFailure