#
# *******************************************************************************
# * Copyright © Temenos Headquarters SA 2021. All rights reserved.
# *******************************************************************************
#

apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentorder-db-postgres
  namespace: postgresql
spec:
  selector:
    matchLabels:
      name: paymentorder-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: paymentorder-db
    spec:
      imagePullSecrets:
      - name: paymentorderregcredentials
      containers:
        - name: paymentorder-db
          image: paymentorder.azurecr.io/ms-paymentorder-postgres:latest
          env:
            - name: POSTGRES_DB
              value: paymentorder-db
          # Use secret in real usage
            - name: POSTGRES_PASSWORD
              value: paymentorderpass 
          # Use secret in real usage
            - name: POSTGRES_USER
              value: paymentorderusr            
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 5432
--- 