#
# *******************************************************************************
# * Copyright © Temenos Headquarters SA 2021. All rights reserved.
# *******************************************************************************
#

apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: payments-api-undertow
  namespace: payments
spec:
  template:
    spec:
      containers:
        - image: dev.local/temenos/ms-paymentorder-service:DEV
          ports:
          - name: http1
            containerPort: 8080
          envFrom:
            - configMapRef:
                name: payments-api-config
          env:
          # Use secret in real usage
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: posqldbsecret
                  key: USER_NAME 
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: posqldbsecret
                  key: PASSWORD     