apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: payments-ingester-avro
  namespace: payments
spec:
  template:
    spec:
      containers:
        - image: dev.local/temenos/ms-paymentorder-ingester:DEV
          ports:
          - name: http1
            containerPort: 8080
          envFrom:
            - configMapRef:
                name: payments-ingester-avro-config
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: payments-ingester-command
  namespace: payments
spec:
  template:
    spec:
      containers:
        - image: dev.local/temenos/ms-paymentorder-ingester:DEV
          ports:
          - name: http1
            containerPort: 8080
          envFrom:
            - configMapRef:
                name: payments-ingester-command-config
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: payments-ingester-eventingester
  namespace: payments
spec:
  template:
    spec:
      containers:
        - image: dev.local/temenos/ms-paymentorder-ingester:DEV
          ports:
          - name: http1
            containerPort: 8080
          envFrom:
            - configMapRef:
                name: payments-ingester-event-config
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: payments-ingester-eventdelivery
  namespace: payments
spec:
  template:
    spec:
      containers:
        - image: dev.local/temenos/ms-paymentorder-ingester:DEV
          ports:
          - name: http1
            containerPort: 8080
          envFrom:
            - configMapRef:
                name: payments-eventdelivery-config