#
# *******************************************************************************
# * Copyright © Temenos Headquarters SA 2021. All rights reserved.
# *******************************************************************************
#

apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentorder-db
  namespace: payments
spec:
  selector:
    matchLabels:
      name: paymentorder-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: paymentorder-db
    spec:
      containers:
      - image: temenos/ms-paymentorder-mssql:DEV
        env:
          # Use secret in real usage
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: posqldbsecret
              key: USER_NAME
        - name: SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: posqldbsecret
              key: PASSWORD
        - name: ACCEPT_EULA
          value: "Y"     
        imagePullPolicy: IfNotPresent
        name: paymentorder-db
        ports:
        - containerPort: 1433
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: paymentorder-db-service
  name: paymentorder-db-service
  namespace: payments
spec:
  type: NodePort
  ports:
  - name: "1433"
    port: 1433
    nodePort: 30015
  selector:
    name: paymentorder-db