#
# *******************************************************************************
# * Copyright © Temenos Headquarters SA 2021. All rights reserved.
# *******************************************************************************
#

ARG DB_BASE_IMAGE
FROM ${DB_BASE_IMAGE}

ADD initmsdb.sql /docker-entrypoint-initdb.d/