#
# *******************************************************************************
# * Copyright © Temenos Headquarters SA 2021. All rights reserved.
# *******************************************************************************
#

apiVersion: v1
kind: Service
metadata:
  name: paymentorder-poapisvcnp
  labels:
    app.kubernetes.io/name: paymentorder-poapisvcnp
spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
      protocol: TCP
      nodePort: 30020 
  selector:
    app: paymentorder-api