# Default values for dbInitialisation.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  sqlinit:
    repository: temenos/ms-paymentorder-appinit
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: DEV

# Set the pull secret name here
#imagePullSecrets: all-icr-io

restartPolicy: OnFailure

env:
  sqlinit:
    ##MySQL
    databaseKey: sql
    databaseName: payments
    dbdialect: 
    dbusername: 
    dbpassword: 
    dbconnectionurl:
    dbdriver:
    dbautoupgrade: "N"    
    
    ##MSSQL
    # databaseKey: sql
    # databaseName: payments
    # dbdialect: org.hibernate.dialect.SQLServer2012Dialect
    # dbusername: sa
    # dbpassword: Rootroot@12345
    # dbconnectionurl: jdbc:sqlserver://db-service:1433;databaseName=payments
    # msversion: DEV.0.0-SNAPSHOT   
    # dbdriver: com.microsoft.sqlserver.jdbc.SQLServerDriver     
    # migration: path:database/install/     

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

