apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: payments-scheduler
  namespace: {{.Values.paymentsnamespace}}
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: payments-scheduler
            image: "{{ .Values.image.paymentorderscheduler.repository }}:{{ .Values.image.paymentorderscheduler.tag | default .Chart.AppVersion }}"
            imagePullPolicy: "{{ .Values.image.paymentorderscheduler.pullPolicy }}"
            env:
              - name: HOST
                value: {{ .Values.env.database.host | quote }} 
              - name: PORT
                value: {{ .Values.env.database.port | quote }}
              - name: DATABASE_NAME
                value: {{ .Values.env.database.database_name | quote }}
              - name: DB_USERNAME
                value: {{ .Values.env.database.db_username | quote }}
              - name: DB_PASSWORD
                value: {{ .Values.env.database.db_password | quote }} 
              - name: DRIVER_NAME
                value: {{ .Values.env.database.driver_name | quote }}
              - name: DIALECT
                value: {{ .Values.env.database.dialect | quote }} 
              - name: DB_CONNECTION_URL
                value: {{ .Values.env.database.db_connection_url | quote }} 
              - name: MAX_POOL_SIZE
                value: {{ .Values.env.database.max_pool_size | quote }} 
              - name: MIN_POOL_SIZE
                value: {{ .Values.env.database.min_pool_size | quote }}
              - name: DATABASE_KEY
                value: {{ .Values.env.database.database_key | quote }} 
              - name: temn.msf.name
                value: {{ .Values.env.paymentorderscheduler.temn_msf_name }} 
              - name: temn.msf.security.authz.enabled
                value: {{ .Values.env.paymentorderscheduler.temn_msf_security_authz_enabled | quote }}             
              - name: className_paymentscheduler
                value: {{ .Values.env.paymentorderscheduler.className_paymentscheduler }} 
              - name: className_nosqlInboxCatchup
                value: {{ .Values.env.paymentorderscheduler.className_nosqlInboxCatchup }} 
              - name: className_nosqlOutboxCatchup
                value: {{ .Values.env.paymentorderscheduler.className_nosqlOutboxCatchup }}         
              - name: operationId
                value: {{ .Values.env.paymentorderscheduler.operationId }}             
          restartPolicy: OnFailure