#
# *******************************************************************************
# * Copyright © Temenos Headquarters SA 2021. All rights reserved.
# *******************************************************************************
#

apiVersion: batch/v1
kind: Job
metadata:
  name: payments-mdal-extract-job
  namespace: payments
spec:
  template:
    spec:
      containers:
      - name: paymentms-job
        image: "{{ .Values.image.paymentordermdal.repository }}:{{ .Values.image.paymentordermdal.tag | default .Chart.AppVersion }}"
        envFrom:
          - configMapRef:
              name: payments-mdal-config                  
        env:
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: posqldbsecret
                key: USER_NAME 
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: posqldbsecret
                key: PASSWORD                     
      restartPolicy: OnFailure