#
# *******************************************************************************
# * Copyright © Temenos Headquarters SA 2021. All rights reserved.
# *******************************************************************************
#

apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "appinit.name" . }}{{ "-app-init" }}
  labels:
    app.kubernetes.io/name: {{ include "appinit.name" . }}{{ "-app-init" }}
    helm.sh/chart: {{ include "appinit.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}  
spec:
  template:
    metadata:
      name: {{ include "appinit.name" . }}{{ "-app-init" }}
    spec:
   {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
      - name: {{ .Values.imagePullSecrets }} 
    {{- end }}    
      containers:
      - name: {{ include "appinit.name" . }}{{ "-app-init" }}
        image: "{{ .Values.image.appinit.repository }}" 
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        env: 
          - name: database.key
            value: {{ .Values.env.appinit.databaseKey }} 
          - name: database.name
            value: {{ .Values.env.appinit.databaseName }} 
          - name: db.connection.url
            value: {{ .Values.env.appinit.dbConnectionUrl }} 
          - name: db.auto.upgrade
            value: {{ .Values.env.appinit.dbautoupgrade | quote }}    
          - name: temn.msf.logger.exportType
            value: {{ .Values.env.appinit.exportType }} 
          - name: temn.msf.logger.socketHost
            value: {{ .Values.env.appinit.socketHost | quote }} 
          - name: temn.msf.logger.socketPort
            value: {{ .Values.env.appinit.socketPort | quote }}
        {{- if and (eq .Values.env.dbcred "Y") (eq .Values.env.appinit.databaseKey "postgresql") }}
          - name: db.username
            valueFrom:
              secretKeyRef:
                name: appinitsecret
                key: POSTGRES_USER_NAME 
          - name: db.password
            valueFrom:
              secretKeyRef:
                name: appinitsecret
                key: POSTGRES_PASSWORD   
        {{- else if and (eq .Values.env.dbcred "Y") (eq .Values.env.appinit.databaseKey "mongodb") }}
          - name: db.username
            valueFrom:
              secretKeyRef:
                name: appinitsecret
                key: MONGO_USER_NAME 
          - name: db.password
            valueFrom:
              secretKeyRef:
                name: appinitsecret
                key: MONGO_PASSWORD 
        {{ else }}
          - name: db.username
            value: {{ .Values.env.appinit.dbUserName }} 
          - name: db.password
            value: {{ .Values.env.appinit.dbPassword }}
        {{- end }}
      restartPolicy: {{ .Values.restartPolicy }} 