apiVersion: batch/v1
kind: Job
metadata:
  name: party-mdal-extract-job
  namespace: party
spec:
  template:
    spec:
      containers:
      - name: partyms-job
        image: "{{ .Values.image.paymentorderscheduler.repository }}:{{ .Values.image.paymentorderscheduler.tag | default .Chart.AppVersion }}"
        imagePullPolicy: "{{ .Values.image.paymentorderscheduler.pullPolicy }}"
		envFrom:
          - configMapRef:
              name: payments-mdal-config                  
		env:
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: posqldbsecret
                key: USER_NAME 
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: posqldbsecret
                key: PASSWORD                     
      restartPolicy: OnFailure          