#
# *******************************************************************************
# * Copyright © Temenos Headquarters SA 2021. All rights reserved.
# *******************************************************************************
#

apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-scheduler
  namespace: {{.Values.paymentsnamespace}}
spec:
  selector:
    matchLabels:
      app: payments-scheduler
  template:
    metadata:
      labels:
        app: payments-scheduler   
    spec:
      containers:
      - name: payments-scheduler-config
        image: "{{ .Values.image.paymentorderscheduler.repository }}:{{ .Values.image.paymentorderscheduler.tag | default .Chart.AppVersion }}"
        imagePullPolicy: "{{ .Values.image.paymentorderscheduler.pullPolicy }}"
        envFrom:
          - configMapRef:
              name: payments-scheduler-config
        env:
          # Use secret in real usage
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: posqldbsecret
                key: USER_NAME 
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: posqldbsecret
                key: PASSWORD
--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqlinboxcatchup-scheduler-config
  namespace: {{.Values.paymentsnamespace}}
spec:
  selector:
    matchLabels:
      app: sqlinboxcatchup-scheduler-config
  template:
    metadata:
      labels:
        app: sqlinboxcatchup-scheduler-config     
    spec:
      containers:
      - name: sqlinboxcatchup-scheduler-config
        image: "{{ .Values.image.paymentorderscheduler.repository }}:{{ .Values.image.paymentorderscheduler.tag | default .Chart.AppVersion }}"
        imagePullPolicy: "{{ .Values.image.paymentorderscheduler.pullPolicy }}"
        envFrom:
          - configMapRef:
              name: sqlinboxcatchup-scheduler-config
        env:
          # Use secret in real usage
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: posqldbsecret
                key: USER_NAME 
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: posqldbsecret
                key: PASSWORD                 
        