apiVersion: apps/v1
kind: Deployment
metadata:    
  name: paymentorder-db       
spec:
  selector:
    matchLabels:
      name: paymentorder-db
  replicas: 1
  strategy: {}
  template:
    metadata:      
      labels:
        name: paymentorder-db
    spec:
      containers:
        image: ms-paymentorder-mysql
        imagePullPolicy: IfNotPresent
        name: paymentorder-db        
        ports:
        - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: paymentorder-db-service
  name: paymentorder-db-service
spec:
  type: NodePort
  ports:
  - name: "3306"
    port: 3306
    nodePort: 3306
  selector:
    name: paymentorder-db