apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "paymentorder.name" . }}{{ "-scheduler" }}
  namespace: {{ .Values.namespace }}
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: {{ include "paymentorder.name" . }}{{ "-scheduler" }}
            image: "{{ .Values.image.paymentorderscheduler.repository }}:{{ .Values.image.paymentorderscheduler.tag | default .Chart.AppVersion }}"
            imagePullPolicy: "{{ .Values.image.paymentorderscheduler.pullPolicy }}"
            env:
              - name: DATABASE_KEY
                value: {{ .Values.env.database.DATABASE_KEY }} 
              - name: MONGODB_DBNAME
                value: {{ .Values.env.database.MONGODB_DBNAME }} 
              - name: MONGODB_CONNECTIONSTR
                value: {{ .Values.env.database.MONGODB_CONNECTIONSTR }} 
            envFrom:
              - configMapRef:
                  name: paymentorder-scheduler-config                
          restartPolicy: OnFailure