#
# *******************************************************************************
# * Copyright © Temenos Headquarters SA 2021. All rights reserved.
# *******************************************************************************
#

apiVersion: v1
kind: ConfigMap
metadata:
  name: paymentorder-mongo-db-config
  namespace: paymentorder
data:
  DATABASE_KEY: mongodb
  MONGODB_DBNAME: ms_paymentorder
  MONGODB_CONNECTIONSTR: mongodb://mongodb-0.mongodb-svc.mongodb.svc.cluster.local:27017,mongodb-1.mongodb-svc.mongodb.svc.cluster.local:27017,mongodb-2.mongodb-svc.mongodb.svc.cluster.local:27017  
---