apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: paymentorder-api
  namespace: paymentorder
spec:
  template:
    spec:
      containers:
        - image: dev.local/temenos/ms-paymentorder-service:DEV
          ports:
          - name: http1
            containerPort: 8080
          envFrom:
            - configMapRef:
                name: paymentorder-api-config
            - configMapRef:
                name: paymentorder-mongo-db-config