# Default values for holdingsmsvc.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: paymentorder

replicacount:
  paymentorderapi: 1
  paymentorderingester: 1
  schemaregistry: 1
  
  
kafkatopic:
  topicpartitions: 3
  retentionms: 7200000
  segmentbytes: 1073741824
  replicas: 3
  avrotopic: table-update-paymentorder
  outboxtopic: paymentorder-outbox
  eventstoretopic: ms-eventstore-inbox-topic
  inboxtopic: ms-paymentorder-inbox-topic
  eventtopic: paymentorder-event-topic
  errortopic: error-paymentorder
  inboxerrortopic: ms-paymentorder-inbox-error-topic
  errorstreamproducerid: ms-paymentorder-ingester-error-producer
  consumergroupid: ms-paymentorder-ingester-consumer
  multiparttopic: multipart-topic
  


image:
  paymentorderapi:
    repository: dev.local/temenos/ms-paymentorder-service
    tag: 
    pullPolicy: Never
  paymentorderingester:
    repository: dev.local/temenos/ms-paymentorder-ingester
    tag: DEV
    pullPolicy: Never
  paymentorderinboxoutbox:
    repository: dev.local/temenos/ms-paymentorder-inboxoutbox
    tag: DEV
    pullPolicy: Never  
  schemaregistry:
    repository: confluentinc/cp-schema-registry
    tag: 5.3.0
    pullPolicy: Never
  paymentorderscheduler:
    repository: dev.local/temenos/ms-paymentorder-scheduler
    tag: DEV
    pullPolicy: Never
  fileingester:
    repository: dev.local/temenos/ms-paymentorder-fileingester
    tag: DEV
    pullPolicy: Never     

apideployment: paymentorder-api
schemaregistry: schema-registry
schemaregistrysvc: schema-registry-svc


env:
  database:
    DATABASE_KEY: 
    MONGODB_DBNAME: 
    MONGODB_CONNECTIONSTR: mongodb://mongodb-0.mongodb-svc.mongodb.svc.cluster.local:27017,mongodb-1.mongodb-svc.mongodb.svc.cluster.local:27017,mongodb-2.mongodb-svc.mongodb.svc.cluster.local:27017
    #If the below variable is set to "Y", secrets will be enabled 
    MONGO_CRED: "N"
    
    #MONGODB_USER : root
    #MONGODB_PASS : ENC(0jDFL9aa9VbB/KfSH6zfEQ==)
    
     #POSTGRESQL:
    
    #If the below variable is set to "Y", secrets will be enabled 
    POSTGRESQL_CRED: "N"
    
    POSTGRESQL_CONNECTIONURL:
    POSTGRESQL_POOLSIZE: "10"
    POSTGRESQL_USERNAME: paymentorderusr
    POSTGRESQL_PASSWORD: paymentorderpass
    
    #For encrypted password,
    #POSTGRESQL_PASSWORD: ENC(0QEqdsmi+qUTOAINlDjzKmLl9TIdoN4g7szv2l2u25Q=)

    #Use the below 2 variables to decrypt the encrypted password
    temn_msf_db_pass_encryption_key: temenos
    temn_msf_db_pass_encryption_algorithm: PBEWithMD5AndTripleDES    
    
  kafka:
    temnmsfstreamvendor: kafka
    temnqueueimpl: kafka
    generic_ip: 127.0.0.1
    kafkabootstrapservers: my-cluster-kafka-bootstrap.kafka:9092
    schema_registry_url: http://schema-registry-svc.kafka.svc.cluster.local
    kafkaAliases: "N"
    
    kafkaip:
    kafka0ip:
    kafka1ip:
    kafka2ip:
    devdomain:
    
    kafkaHostName:
    kafka0HostName:
    kafka1HostName:
    kafka2HostName:
    devdomainHostName:
  scheduler:
    temn_msf_scheduler_nosqlInboxCatchup_cron_trigger_time: 0 */30 * ? * * 
    temn_msf_scheduler_nosqlOutboxCatchup_cron_trigger_time: 0 */30 * ? * *
    temn_msf_scheduler_adapterscheduler_cron_trigger_time: 59 * * ? * *
    schedule: "*/5 * * * *"    
  schemaregistry:
    SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://my-cluster-kafka-bootstrap.kafka:9092
    SCHEMA_REGISTRY_HOST_NAME: schema-registry
    SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
    SCHEMA_REGISTRY_CUB_KAFKA_TIMEOUT: "500"
    SCHEMA_REGISTRY_CUB_ZK_TIMEOUT: "500"
    SCHEMA_REGISTRY_KAFKASTORE_SECURITY_PROTOCOL: PLAINTEXT
  nosqlinboxcatchupscheduler:
    temn_msf_scheduler_inboxcleanup_schedule: "60"
    schedule: 5    

service:
  paymentorderapi:
    type: LoadBalancer
    port: 80
  schemaregistry:
    type: ClusterIP
    port: 80
    targetport: 8081
  schemaregistrynp:
    type: NodePort
    port: 8081
    nodeport: 32101    

ports:
  name: http
  port: 8080
  protocol: TCP
  targetport: 30020
  
external:
  enabled: true
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  
msf:
  jms:
    provider: tcp://10.92.4.94:61616
    factory: org.apache.activemq.jndi.ActiveMQInitialContextFactory
    vendor: activemq
  
  debulking:
    retryTime: 100
    jobrecordlistsize: 10

  ingest:
    cloudevent: true

  scheduler:
    threadexecutor: 8
    kubernetes: true
    config: false

  others:
    name: ms-paymentorder
    execenv: server
    authzenabled: false

inboxoutbox:
  inbox:
    threadpoolcount: 2
    namespace: paymentorder-inbox

  outbox:
   threadpoolcount: 2
   namespace: paymentorder-outbox   
     
logging:
#  socketHost: #ipaddress
#  socketPort: #port
  exportType: #socket (console,socket)
  
metrics:
  #publisherPort: 9091 
  #publisherHost: 192.168.228.193
  metricsDisabled: "true"

pit:
  JWT_TOKEN_ISSUER:
  JWT_TOKEN_PRINCIPAL_CLAIM:
  ID_TOKEN_SIGNED:
  JWT_TOKEN_PUBLIC_KEY:
  JWT_TOKEN_PUBLIC_KEY_CERT_ENCODED:   

# Set the pull secret name here
imagePullSecrets: 