#-------------------------------------------------------------
#- Docker compose base definition file to run containers.
#-----------------------------------------------------------
---
version: '3.6'
services:
  db-service:
    build:
      context: ${DB_CONTEXT}
      dockerfile: Dockerfile
      args:
        DB_BASE_IMAGE: ${DB_BASE_IMAGE}
    image: ${DB_IMAGE}
    shm_size: '1gb'
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: payments
  
  api:
    build:
      context: ${API_CONTEXT}
      dockerfile: Dockerfile
      args:
        API_BASE_IMAGE: ${API_BASE_IMAGE}
        api_artifactid: ${api_artifactid}
        api_java_options: ${java_options} ${REMOTE_DEBUG}
    image: ${API_IMAGE}
    depends_on:
      - db-service
    ports:
      - "8090:8080"
      - "40508:40500"
    environment:
      HOST: db-service
      PORT: 3306
      DATABASE_NAME: payments
      DB_USERNAME: root
      DB_PASSWORD: root
      DRIVER_NAME: com.mysql.jdbc.Driver
      DIALECT: org.hibernate.dialect.MySQL5InnoDBDialect
      DB_CONNECTION_URL: jdbc:mysql://db-service:3306/payments
      className_CreateNewPaymentOrder: com.temenos.microservice.payments.function.CreateNewPaymentOrderImpl
      VALIDATE_PAYMENT_ORDER: "false"
      className_GetPaymentOrders: com.temenos.microservice.payments.function.GetPaymentOrdersImpl
      className_UpdatePaymentOrder: com.temenos.microservice.payments.function.UpdatePaymentOrderImpl
      className_GetPaymentOrder: com.temenos.microservice.payments.function.GetPaymentOrderImpl
      className_invokePaymentState: com.temenos.microservice.payments.function.InvokePaymentOrderImpl
      DATABASE_KEY: sql
      PDP_CONFIG: classpath:xacml/payments-pdp-config.xml
      temn.msf.name: PaymentOrder
      temn.msf.security.authz.enabled: "false"
      class.inbox.dao: com.temenos.microservice.framework.core.inbox.InboxDaoImpl
      class.outbox.dao: com.temenos.microservice.framework.core.outbox.OutboxDaoImpl
  
  ingester:
    build:
      context: ${INGESTER_CONTEXT}
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: ${INGESTER_APP_BASE_IMAGE}
        artifactid: ${ingester_artifactid}
        java_options: ${java_options} ${REMOTE_DEBUG}
    image: ${INGESTER_IMAGE}
    depends_on:
      - db-service
    ports:
      - "40509:40500"
    environment:
      HOST: db-service
      PORT: 3306
      DATABASE_NAME: payments
      DB_USERNAME: root
      DB_PASSWORD: root
      DRIVER_NAME: com.mysql.jdbc.Driver
      DIALECT: org.hibernate.dialect.MySQL5InnoDBDialect
      DB_CONNECTION_URL: jdbc:mysql://db-service:3306/payments
      temn.msf.name: PaymentOrder
      temn.msf.stream.vendor: kafka
      temn.msf.schema.registry.url: http://schema-registry:8081
      temn.msf.stream.kafka.bootstrap.servers: kafka:29092
      temn.msf.ingest.source.stream: table-update-paymentorder
      temn.msf.ingest.source.stream.consumergroup.id: msf-paymentorder-ingester-consumer
      temn.msf.ingest.sink.error.stream: error-paymentorder
      temn.msf.ingest.sink.error.stream.producer.id: msf-paymentorder-ingester-error-producer
      temn.msf.security.authz.enabled: "false"
      temn.msf.ingest.event.ingester: com.temenos.microservice.framework.core.ingester.MicroserviceIngester
      PAYMENT_ORDEREvent: com.temenos.microservice.payments.ingester.PaymentorderIngesterUpdater
      DATABASE_KEY: sql
  
  stateingester:
    build:
      context: ${INGESTER_CONTEXT}
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: ${INGESTER_APP_BASE_IMAGE}
        artifactid: ${ingester_artifactid}
        java_options: ${java_options} ${REMOTE_DEBUG}
    image: ${INGESTER_IMAGE}
    depends_on:
      - db-service
    ports:
      - "40511:40501"
    environment:
      HOST: db-service
      PORT: 3306
      DATABASE_NAME: payments
      DB_USERNAME: root
      DB_PASSWORD: root
      DRIVER_NAME: com.mysql.jdbc.Driver
      DIALECT: org.hibernate.dialect.MySQL5InnoDBDialect
      DB_CONNECTION_URL: jdbc:mysql://db-service:3306/payments
      temn.msf.name: PaymentOrder
      temn.msf.stream.vendor: kafka
      temn.msf.schema.registry.url: http://schema-registry:8081
      temn.msf.stream.kafka.bootstrap.servers: kafka:29092
      temn.msf.ingest.source.stream: table-update-state
      temn.msf.ingest.source.stream.consumergroup.id: msf-paymentorder-ingester-consumer
      temn.msf.ingest.sink.error.stream: error-paymentorder
      temn.msf.ingest.sink.error.stream.producer.id: msf-paymentorder-ingester-error-producer
      temn.msf.security.authz.enabled: "false"
      temn.ingester.business.group.id: msf-test-group-id
      temn.ingester.business.topic: table-update-business
      temn.msf.ingest.generic.ingester:  com.temenos.microservice.payments.ingester.PaymentOrderStateIngester
      temn.msf.ingest.is.avro.event.ingester: "false"
      temn.iris.fdata.enquiry.base.path: http://10.92.4.84:9089/irf-provider-container/api/v1.0.0/
      temn.iris.fdata.enquiry.resource.path: system/events/pendingEvents
      temn.msf.security.authz.enabled: "false"
      class.inbox.dao: com.temenos.microservice.framework.core.inbox.InboxDaoImpl
      class.outbox.dao: com.temenos.microservice.framework.core.outbox.OutboxDaoImpl
      DATABASE_KEY: sql
      EXECUTION_ENVIRONMENT: TEST
  
  businessingester:
    build:
      context: ${INGESTER_CONTEXT}
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: ${INGESTER_APP_BASE_IMAGE}
        artifactid: ${ingester_artifactid}
        java_options: ${java_options} ${REMOTE_DEBUG}
    image: ${INGESTER_IMAGE}
    depends_on:
      - db-service
    ports:
      - "40512:40504"
    environment:
      HOST: db-service
      PORT: 3306
      DATABASE_NAME: payments
      DB_USERNAME: root
      DB_PASSWORD: root
      DRIVER_NAME: com.mysql.jdbc.Driver
      DIALECT: org.hibernate.dialect.MySQL5InnoDBDialect
      DB_CONNECTION_URL: jdbc:mysql://db-service:3306/payments
      temn.msf.name: PaymentOrder
      temn.msf.stream.vendor: kafka
      temn.msf.schema.registry.url: http://schema-registry:8081
      temn.msf.stream.kafka.bootstrap.servers: kafka:29092
      temn.msf.ingest.source.stream: table-update-business
      temn.msf.ingest.source.stream.consumergroup.id: msf-test-group-id
      temn.msf.ingest.sink.error.stream: error-paymentorder
      temn.msf.ingest.sink.error.stream.producer.id: msf-paymentorder-ingester-error-producer
      temn.msf.ingest.generic.ingester:  com.temenos.microservice.payments.ingester.PaymentOrderBusinessIngester
      temn.msf.security.authz.enabled: "false"
      temn.msf.ingest.is.avro.event.ingester: "false"
      class.inbox.dao: com.temenos.microservice.framework.core.inbox.InboxDaoImpl
      class.outbox.dao: com.temenos.microservice.framework.core.outbox.OutboxDaoImpl
      temn.msf.security.authz.enabled: "false"
      temn.msf.ingest.consumer.max.poll.records: "1"
      DATABASE_KEY: sql
      
  ingesterbinary:
    build:
      context: ${INGESTER_CONTEXT}
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: ${INGESTER_APP_BASE_IMAGE}
        artifactid: ${ingester_artifactid}
        java_options: ${java_options} ${REMOTE_DEBUG}
    image: ${INGESTER_IMAGE}
    depends_on:
      - db-service
    ports:
      - "40510:40500"
    environment:
      HOST: db-service
      PORT: 3306
      DATABASE_NAME: payments
      DB_USERNAME: root
      DB_PASSWORD: root 
      DRIVER_NAME: com.mysql.jdbc.Driver
      DIALECT: org.hibernate.dialect.MySQL5InnoDBDialect
      DB_CONNECTION_URL: jdbc:mysql://db-service:3306/payments
      temn.msf.name: PaymentOrder
      temn.msf.stream.vendor: kafka
      temn.msf.stream.kafka.bootstrap.servers: kafka:29092
      temn.msf.ingest.source.stream: ms-paymentorder-inbox-topic
      temn.msf.ingest.source.stream.consumergroup.id: ms-paymentorder-ingester-consumer
      temn.msf.ingest.sink.enabled: "true"
      temn.msf.ingest.sink.stream:
      temn.msf.ingest.sink.stream.producer.id: ms-paymentorder-ingester-sink-producer
      temn.msf.ingest.sink.error.enabled: "false"
      temn.msf.ingest.sink.error.stream: ms-paymentorder-inbox-error-topic
      temn.msf.ingest.sink.error.stream.producer.id: ms-paymentorder-ingester-error-producer
      temn.msf.stream.kafka.transaction.enabled: "true"
      temn.msf.stream.ms.data.transaction.enabled: "true"
      temn.msf.ingest.generic.ingester: com.temenos.microservice.framework.core.ingester.GenericCommandSTBinaryIngester
      temn.msf.exec.env: server
      temn.msf.stream.outbox.topic: ms-paymentorder-outbox-topic
      temn.msf.function.class.CreateNewPaymentOrder: com.temenos.microservice.payments.function.CreateNewPaymentOrderImpl
      class.package.name: com.temenos.microservice.payments.function
      class.inbox.dao: com.temenos.microservice.framework.core.inbox.InboxDaoImpl
      class.outbox.dao: com.temenos.microservice.framework.core.outbox.OutboxDaoImpl
      temn.msf.ingest.is.avro.event.ingester: "false"
      temn.msf.security.authz.enabled: "false"
      temn.msf.ingest.consumer.max.poll.records: "1"
      DATABASE_KEY: sql
      VALIDATE_PAYMENT_ORDER: "false"