#-------------------------------------------------------------
#- Docker compose base definition file to run containers.
#-----------------------------------------------------------
---
version: '3.6'
networks:
 default:
  external:
   name: ${DEFAULT_NETWORK_NAME}
services:
  api:
    build:
      context: ${API_CONTEXT}
      dockerfile: Dockerfile
      args:
        API_BASE_IMAGE: ${API_BASE_IMAGE}
        api_artifactid: ${api_artifactid}
        api_java_options: ${java_options} ${REMOTE_DEBUG}
    image: ${API_IMAGE}
    ports:
      - "8090:8080"
      - "40510:40500"
    environment:
      HOST: db-service
      PORT: 3306
      DATABASE_NAME: payments
      DB_USERNAME: root
      DB_PASSWORD: root
      DRIVER_NAME: com.mysql.jdbc.Driver
      DIALECT: org.hibernate.dialect.MySQL5InnoDBDialect
      DB_CONNECTION_URL: jdbc:mysql://db-service:3306/payments
      MAX_POOL_SIZE: 150
      MIN_POOL_SIZE: 10  
      className_CreateNewPaymentOrder: com.temenos.microservice.payments.function.CreateNewPaymentOrderImpl
      className_CreateNewPaymentOrders: com.temenos.microservice.payments.function.CreateNewPaymentOrdersImpl
      className_CreateBalanceAndTransaction: com.temenos.microservice.payments.function.CreateBalanceAndTransactionImpl
      className_UpdateNewPaymentOrders: com.temenos.microservice.payments.function.UpdateNewPaymentOrdersImpl
      VALIDATE_PAYMENT_ORDER: "false"
      className_GetPaymentOrders: com.temenos.microservice.payments.function.GetPaymentOrdersImpl
      className_UpdatePaymentOrder: com.temenos.microservice.payments.function.UpdatePaymentOrderImpl
      className_DeletePaymentOrders: com.temenos.microservice.payments.function.DeletePaymentOrdersImpl
      className_GetPaymentOrder: com.temenos.microservice.payments.function.GetPaymentOrderImpl
      className_invokePaymentState: com.temenos.microservice.payments.function.InvokePaymentOrderImpl
      className_GetPaymentOrderCurrency: com.temenos.microservice.payments.function.GetPaymentOrderCurrencyImpl
      className_getHealthCheck: com.temenos.microservice.framework.core.health.GetHealthCheckImpl  
      className_FileUpload: com.temenos.microservice.payments.function.FileUploadImpl
      className_createReferenceData: com.temenos.microservice.framework.core.data.referencedata.CreateReferenceDataImpl
      className_getReferenceData: com.temenos.microservice.framework.core.data.referencedata.GetReferenceDataImpl
      className_updateReferenceData: com.temenos.microservice.framework.core.data.referencedata.UpdateReferenceDataImpl
      className_addReferenceData: com.temenos.microservice.framework.core.data.referencedata.AddReferenceDataImpl
      className_deleteReferenceData: com.temenos.microservice.framework.core.data.referencedata.DeleteReferenceDataImpl
      className_FileDownload: com.temenos.microservice.payments.function.FileDownloadImpl   
      API_HEALTH_CHECK_BUSINESS_CONDITION: com.temenos.microservice.payments.core.BusinessConditionImpl
      className_CreateEmployee: com.temenos.microservice.payments.function.CreateEmployeeImpl
      className_GetEmployee: com.temenos.microservice.payments.function.GetEmployeeImpl
      className_UpdateEmployee: com.temenos.microservice.payments.function.UpdateEmployeeImpl
      className_DeleteEmployee: com.temenos.microservice.payments.function.DeleteEmployeeImpl
      DATABASE_KEY: sql
      PDP_CONFIG: classpath:xacml/payments-pdp-config.xml
      temn.msf.name: PaymentOrder
      class.inbox.dao: com.temenos.microservice.framework.core.inbox.InboxDaoImpl
      class.outbox.dao: com.temenos.microservice.framework.core.outbox.OutboxDaoImpl
      serviceadaptor.preprocessorimpl.class: com.temenos.microservice.sample.security.SampleTokenGenerator
      temn.msf.stream.vendor: kafka
      temn.queue.impl: kafka
      temn.msf.stream.kafka.bootstrap.servers: kafka:29092
      IRIS_PROTOCOL: http
      IRIS_HOST_IP: 10.92.14.71
      IRIS_PORT: 9089
      IRIS_PATH: irf-provider-container/api
      IRIS_R18_PATH: irisR18/api
      IRIS_VERSION: v1.0.0
      temn.msf.pdp.resource.type: API
      temn.msf.pdp.resource.manager: PAYMENT
      temn.msf.storage.home: ${MS_STORAGE_HOME}
      FILE_STORAGE_URL: ${FILE_STORAGE_URL}
      temn.msf.max.file.upload.size: ${MAX_FILE_UPLOAD_SIZE}
  avroIngester:
    build:
      context: ${INGESTER_CONTEXT}
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: ${INGESTER_APP_BASE_IMAGE}
        artifactid: ${ingester_artifactid}
        java_options: ${java_options} ${REMOTE_DEBUG}
    image: ${INGESTER_IMAGE}
    ports:
      - "40518:40500"
      - "8082:8080"
    environment:
      HOST: db-service
      PORT: 3306
      DATABASE_NAME: payments
      DATABASE_KEY: sql
      DB_USERNAME: root
      DB_PASSWORD: root
      DRIVER_NAME: com.mysql.jdbc.Driver
      DIALECT: org.hibernate.dialect.MySQL5InnoDBDialect
      DB_CONNECTION_URL: jdbc:mysql://db-service:3306/payments
      MAX_POOL_SIZE: 150
      MIN_POOL_SIZE: 10  
      temn.msf.name: ms-paymentorder
      temn.queue.impl: kafka
      temn.msf.stream.vendor: kafka
      temn.msf.schema.registry.url: http://schema-registry:8081
      temn.msf.stream.kafka.bootstrap.servers: kafka:29092
      temn.msf.ingest.source.stream: table-update-avroIngester
      temn.msf.ingest.source.stream.consumergroup.id: msf-payments-ingester-consumer1
      temn.msf.ingest.sink.error.stream: error-payments
      temn.msf.ingest.sink.error.stream.producer.id: msf-payments-ingester-error-producer1
      temn.msf.ingest.event.ingester: com.temenos.microservice.framework.core.ingester.MicroserviceIngester
      PAYMENT_ORDEREvent: com.temenos.microservice.payments.ingester.PaymentorderIngesterCommandUpdater
      temn.msf.security.authz.enabled: "false"
      class.inbox.dao: com.temenos.microservice.framework.core.inbox.InboxDaoImpl
      class.outbox.dao: com.temenos.microservice.framework.core.outbox.OutboxDaoImpl
      temn.msf.ingest.consumer.max.poll.records: "1"
      PDP_CONFIG: classpath:xacml/payments-pdp-config.xml
      temn.msf.pdp.resource.type: API
      temn.msf.pdp.resource.manager: PAYMENT
  avroJoltConfigIngester:
    build:
      context: ${INGESTER_CONTEXT}
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: ${INGESTER_APP_BASE_IMAGE}
        artifactid: ${ingester_artifactid}
        java_options: ${java_options} ${REMOTE_DEBUG}
    image: ${INGESTER_IMAGE}
    ports:
      - "40517:40500"
      - "8086:8080"
    environment:
      HOST: db-service
      PORT: 3306
      DATABASE_NAME: payments
      DB_USERNAME: root
      DB_PASSWORD: root
      DRIVER_NAME: com.mysql.jdbc.Driver
      DIALECT: org.hibernate.dialect.MySQL5InnoDBDialect
      DB_CONNECTION_URL: jdbc:mysql://db-service:3306/payments
      MAX_POOL_SIZE: 150
      MIN_POOL_SIZE: 10
      DATABASE_KEY: sql
      temn.msf.name: ms-paymentorder
      temn.queue.impl: kafka
      temn.msf.stream.vendor: kafka
      temn.msf.schema.registry.url: http://schema-registry:8081
      temn.msf.stream.kafka.bootstrap.servers: kafka:29092
      temn.msf.ingest.source.stream: table-update-avroJoltConfigIngester
      temn.msf.ingest.source.stream.consumergroup.id: msf-payments-ingester-consumer1
      temn.msf.ingest.sink.error.stream: error-payments
      temn.msf.ingest.sink.error.stream.producer.id: msf-payments-ingester-error-producer1
      temn.msf.ingest.event.ingester: com.temenos.microservice.framework.core.ingester.MicroserviceIngester
      PAYMENT_ORDEREvent: CreateNewPaymentOrder
      temn.msf.security.authz.enabled: "false"
      class.inbox.dao: com.temenos.microservice.framework.core.inbox.InboxDaoImpl
      class.outbox.dao: com.temenos.microservice.framework.core.outbox.OutboxDaoImpl
      temn.msf.ingest.consumer.max.poll.records: "1"
      PDP_CONFIG: classpath:xacml/payments-pdp-config.xml
      temn.msf.pdp.resource.type: API
      temn.msf.pdp.resource.manager: PAYMENT 
      temn.ingester.mapping.enabled: "true"
      temn.config.file.path: "jolt/" 
      temn.msf.storage.home: "path:etc/configbasedmapping/"
  avroDataEventIngester:
    build:
      context: ${INGESTER_CONTEXT}
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: ${INGESTER_APP_BASE_IMAGE}
        artifactid: ${ingester_artifactid}
        java_options: ${java_options} ${REMOTE_DEBUG}
    image: ${INGESTER_IMAGE}
    ports:
      - "40519:40500"
      - "8083:8080"
    environment:
      HOST: db-service
      PORT: 3306
      DATABASE_NAME: payments
      DATABASE_KEY: sql
      DB_USERNAME: root
      DB_PASSWORD: root
      DRIVER_NAME: com.mysql.jdbc.Driver
      DIALECT: org.hibernate.dialect.MySQL5InnoDBDialect
      DB_CONNECTION_URL: jdbc:mysql://db-service:3306/payments
      MAX_POOL_SIZE: 150
      MIN_POOL_SIZE: 10  
      temn.msf.name: ms-paymentorder
      temn.queue.impl: kafka
      temn.msf.stream.vendor: kafka
      temn.msf.schema.registry.url: http://schema-registry:8081
      temn.msf.stream.kafka.bootstrap.servers: kafka:29092
      temn.msf.ingest.source.stream: table-update-avroDataEventIngester
      temn.msf.ingest.source.stream.consumergroup.id: msf-payments-ingester-consumer1
      temn.msf.ingest.sink.error.stream: error-payments
      temn.msf.ingest.sink.error.stream.producer.id: msf-payments-ingester-error-producer1
      temn.msf.ingest.event.ingester: com.temenos.microservice.framework.core.ingester.MicroserviceIngester
      BALANCE_TRANSACTIONEvent: com.temenos.microservice.payments.ingester.BalanceAndTransactionIngesterCommandUpdater
      temn.msf.security.authz.enabled: "false"
      class.inbox.dao: com.temenos.microservice.framework.core.inbox.InboxDaoImpl
      class.outbox.dao: com.temenos.microservice.framework.core.outbox.OutboxDaoImpl
      temn.msf.ingest.consumer.max.poll.records: "1"
      PDP_CONFIG: classpath:xacml/payments-pdp-config.xml
      temn.msf.pdp.resource.type: API
      temn.msf.pdp.resource.manager: PAYMENT
      temn.msf.ingest.is.multi.event.data: "true"
      temn.msf.ingest.multi.event.ingester.class:  com.temenos.microservice.payments.ingester.BalanceAndTransactionIngesterCommandUpdater
  avroJoltConfigDataEventIngester:
    build:
      context: ${INGESTER_CONTEXT}
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: ${INGESTER_APP_BASE_IMAGE}
        artifactid: ${ingester_artifactid}
        java_options: ${java_options} ${REMOTE_DEBUG}
    image: ${INGESTER_IMAGE}
    ports:
      - "40517:40500"
      - "8086:8080"
    environment:
      HOST: db-service
      PORT: 3306
      DATABASE_NAME: payments
      DB_USERNAME: root
      DB_PASSWORD: root
      DRIVER_NAME: com.mysql.jdbc.Driver
      DIALECT: org.hibernate.dialect.MySQL5InnoDBDialect
      DB_CONNECTION_URL: jdbc:mysql://db-service:3306/payments
      MAX_POOL_SIZE: 150
      MIN_POOL_SIZE: 10
      DATABASE_KEY: sql
      temn.msf.name: ms-paymentorder
      temn.queue.impl: kafka
      temn.msf.stream.vendor: kafka
      temn.msf.schema.registry.url: http://schema-registry:8081
      temn.msf.stream.kafka.bootstrap.servers: kafka:29092
      temn.msf.ingest.source.stream: table-update-avroJoltConfigDataEventIngester
      temn.msf.ingest.source.stream.consumergroup.id: msf-payments-ingester-consumer1
      temn.msf.ingest.sink.error.stream: error-payments
      temn.msf.ingest.sink.error.stream.producer.id: msf-payments-ingester-error-producer1
      temn.msf.ingest.event.ingester: com.temenos.microservice.framework.core.ingester.MicroserviceIngester
      EB_CONTRACT_BALANCESEvent: CreateBalanceAndTransaction
      STMT_ENTRYEvent: CreateBalanceAndTransaction
      temn.msf.security.authz.enabled: "false"
      class.inbox.dao: com.temenos.microservice.framework.core.inbox.InboxDaoImpl
      class.outbox.dao: com.temenos.microservice.framework.core.outbox.OutboxDaoImpl
      temn.msf.ingest.consumer.max.poll.records: "1"
      PDP_CONFIG: classpath:xacml/payments-pdp-config.xml
      temn.msf.pdp.resource.type: API
      temn.msf.pdp.resource.manager: PAYMENT 
      temn.msf.ingest.is.multi.event.data: "true"
      temn.config.file.path: "jolt/" 
      temn.msf.storage.home: "path:etc/configbasedmapping/"
      temn.ingester.mapping.enabled: "true"    
  commandIngester:
    build:
      context: ${INGESTER_CONTEXT}
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: ${INGESTER_APP_BASE_IMAGE}
        artifactid: ${ingester_artifactid}
        java_options: ${java_options} ${REMOTE_DEBUG}
    image: ${INGESTER_IMAGE}
    ports:
      - "40511:40500"
      - "8085:8080"
    environment:
      HOST: db-service
      PORT: 3306
      DATABASE_NAME: payments
      DB_USERNAME: root
      DB_PASSWORD: root
      DRIVER_NAME: com.mysql.jdbc.Driver
      DIALECT: org.hibernate.dialect.MySQL5InnoDBDialect
      DB_CONNECTION_URL: jdbc:mysql://db-service:3306/payments
      MAX_POOL_SIZE: 150
      MIN_POOL_SIZE: 10
      temn.msf.name: ms-paymentorder
      temn.msf.stream.vendor: kafka
      temn.msf.stream.kafka.bootstrap.servers: kafka:29092
      temn.msf.ingest.source.stream: ms-paymentorder-event-topic
      temn.msf.ingest.source.stream.consumergroup.id: ms-paymentorder-ingester-consumer
      temn.msf.ingest.sink.error.stream: ms-paymentorder-inbox-error-topic
      temn.msf.ingest.sink.error.stream.producer.id: ms-paymentorder-ingester-error-producer
      temn.msf.ingest.generic.ingester: com.temenos.microservice.framework.core.ingester.GenericCommandSTBinaryIngester
      temn.msf.exec.env: server
      temn.msf.stream.outbox.topic: ms-paymentorder-outbox-topic
      temn.msf.function.class.CreateNewPaymentOrder: com.temenos.microservice.payments.function.CreateNewPaymentOrderImpl
      temn.msf.function.class.CreateBalanceAndTransaction: com.temenos.microservice.payments.function.CreateBalanceAndTransactionImpl
      class.package.name: com.temenos.microservice.payments.function
      class.inbox.dao: com.temenos.microservice.framework.core.inbox.InboxDaoImpl
      class.outbox.dao: com.temenos.microservice.framework.core.outbox.OutboxDaoImpl
      temn.msf.ingest.is.avro.event.ingester: "false"
      temn.msf.security.authz.enabled: "false"
      DATABASE_KEY: sql
      temn.queue.impl: kafka
      VALIDATE_PAYMENT_ORDER: "false"      
  outboxDeliveryApp:
    build:
      context: ${INBOXOUTBOX_CONTEXT}
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: ${INBOXOUTBOX_BASE_IMAGE}
        artifactid: ${inboxoutbox_artifactid}
        java_options: ${java_options} ${REMOTE_DEBUG}
    image: ${INBOXOUTBOX_IMAGE}
    ports:
      - "40516:40500"
      - "8089:8080"
    environment:
      DATABASE_KEY: sql
      HOST: db-service
      PORT: 3306
      DATABASE_NAME: payments
      DB_USERNAME: root
      DB_PASSWORD: root
      DRIVER_NAME: com.mysql.jdbc.Driver
      DIALECT: org.hibernate.dialect.MySQL5InnoDBDialect
      DB_CONNECTION_URL: jdbc:mysql://db-service:3306/payments
      MAX_POOL_SIZE: 150
      MIN_POOL_SIZE: 10  
      temn.msf.name: ms-paymentorder
      temn.msf.stream.vendor: kafka
      temn.msf.stream.kafka.bootstrap.servers: kafka:29092
      temn.msf.exec.env: server
      temn.msf.stream.outbox.topic: ms-paymentorder-outbox-topic
      temn.msf.function.class.CreateNewPaymentOrder: com.temenos.microservice.payments.function.CreateNewPaymentOrderImpl
      temn.msf.function.class.CreateBalanceAndTransaction: com.temenos.microservice.payments.function.CreateBalanceAndTransactionImpl
      class.package.name: com.temenos.microservice.payments.function
      class.inbox.dao: com.temenos.microservice.framework.core.inbox.InboxDaoImpl
      class.outbox.dao: com.temenos.microservice.framework.core.outbox.OutboxDaoImpl
      temn.msf.security.authz.enabled: "false"
      tmn.inbox.source.namespace: paymentorder-inbox
      tmn.outbox.source.namespace: paymentorder-outbox
      temn.queue.impl: kafka
      tmn.inbox.thread.pool.count: 10
      tmn.outbox.thread.pool.count: 10
      VALIDATE_PAYMENT_ORDER: "false"      