kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ include "paymentorder.name" . }}{{ "-api" }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "paymentorder.name" . }}{{ "-api" }}
    helm.sh/chart: {{ include "paymentorder.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicacount.paymentorderapi }}
{{- end }}
  selector:
    matchLabels:
      {{- include "paymentorderapi.selectorLabels" . | nindent 6 }}
      app: paymentorder-api
  template:
    metadata:
      labels:
        {{- include "paymentorderapi.selectorLabels" . | nindent 8 }}
        app: paymentorder-api
    spec:
    {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
      - name: {{ .Values.imagePullSecrets }} 
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}{{ "-api" }}
          image: "{{ .Values.image.paymentorderapi.repository }}:{{ .Values.image.paymentorderapi.tag | default .Chart.AppVersion }}"
          ports:
            - containerPort: 80
              protocol: TCP
          securityContext:
            privileged: true
          envFrom:
          - configMapRef:
              name: {{ include "paymentorder.name" . }}{{ "-api-config" }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "paymentorder.name" . }}{{ "-poapisvc" }}
  namespace: {{.Values.namespace}}
  labels:
    app.kubernetes.io/name: {{ include "paymentorder.name" . }}{{ "-poapisvc" }}
    helm.sh/chart: {{ include "paymentorder.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.paymentorderapi.type }}
  ports:
    - name: http
      port: {{ .Values.service.paymentorderapi.port }}
      protocol: TCP
      targetPort: 8080
  selector:
    app: {{ .Values.apideployment }}              