#-------------------------------------------------------------
#- Docker compose base definition file to run containers.
#-----------------------------------------------------------

version: '3.6'
services:
  db-init-service:
    build:
      context: ${DB_MIGRATION_CONTEXT}
      dockerfile: db/k8/Dockerfile
      args:
        INGESTER_APP_BASE_IMAGE: ${INGESTER_APP_BASE_IMAGE}
        dbMigration_artifactid: ${dbMigration_artifactid}
    image: ${DB_SCRIPT_IMAGE} 