#-------------------------------------------------------------
#- Docker compose base definition file to run containers with Kafka.
#-------------------------------------------------------------
---
version: '3.6'
services:
  jaeger:
    build:
      context: ${JAEGER_CONTEXT}
      dockerfile: Dockerfile
      args:
        JAEGER_BASE_IMAGE: ${JAEGER_BASE_IMAGE}
    image: ${JAEGER_IMAGE}
    container_name: jaeger
    ports:
      - "16686:16686"
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "14268:14268"
