#-------------------------------------------------------------
#- Docker compose base definition file to run containers.
#-----------------------------------------------------------

version: '3.6'
services:
  cache-service:
    build:
      context: ${CACHE_CONTEXT}
      dockerfile: Dockerfile
      args:
        CACHE_BASE_IMAGE: ${CACHE_BASE_IMAGE}
    image: ${CACHE_BASE_IMAGE}
    ports:
      - "10800:10800"
  db-service1:
    build:
      context: ${DB_CONTEXT}
      dockerfile: Dockerfile
      args:
        DB_BASE_IMAGE: ${DB_BASE_IMAGE}
    container_name: 'mongo1'
    ports:
      - "30001:27017"
  db-service2:
    build:
      context: ${DB_CONTEXT}
      dockerfile: Dockerfile
      args:
        DB_BASE_IMAGE: ${DB_BASE_IMAGE}
    container_name: 'mongo2'
    ports:
      - "30002:27017" 
  db-service3:
    build:
      context: ${DB_CONTEXT}
      dockerfile: Dockerfile
      args:
        DB_BASE_IMAGE: ${DB_BASE_IMAGE}
    container_name: 'mongo3'
    ports:
      - "30003:27017"
  mongosetup:
    container_name: 'mongoinit'
    build:
      context: ${MONGO_INIT_CONTEXT}
      dockerfile: Dockerfile
      args:
        DB_BASE_IMAGE: ${DB_BASE_IMAGE}
    depends_on:
      - db-service1
      - db-service2
      - db-service3
  api:
    build:
      context: ${API_CONTEXT}
      dockerfile: Dockerfile
      args:
        API_BASE_IMAGE: ${API_BASE_IMAGE}
        api_artifactid: ${api_artifactid}
        api_java_options: ${java_options} ${REMOTE_DEBUG}
    image: ${API_IMAGE}
    depends_on:
      - db-service1
      - db-service2
      - db-service3
    ports:
      - "8090:8080"
      - "40509:40500"
    environment:
      DATABASE_KEY: mongodb
      MONGODB_DBNAME: ms_paymentorder
      MONGODB_CONNECTIONSTR: mongodb://mongo1:27017,mongo2:27017,mongo3:27017      
      className_CreateNewPaymentOrder: com.temenos.microservice.paymentorder.function.CreateNewPaymentOrderImpl
      className_GetPaymentOrders: com.temenos.microservice.paymentorder.function.GetPaymentOrdersImpl
      className_UpdatePaymentOrder: com.temenos.microservice.paymentorder.function.UpdatePaymentOrderImpl
      className_GetPaymentOrder: com.temenos.microservice.paymentorder.function.GetPaymentOrderImpl
      className_invokePaymentState: com.temenos.microservice.paymentorder.function.InvokePaymentOrderImpl
      className_getHealthCheck: com.temenos.microservice.framework.core.function.camel.GetHealthCheckImpl
      temn.msf.name: PaymentOrder
      temn.msf.security.authz.enabled: "false"
      temn.msf.stream.vendor: kafka
      temn.msf.stream.kafka.bootstrap.servers: kafka:29092
      class.inbox.dao: com.temenos.microservice.framework.core.inbox.InboxDaoImpl
      class.outbox.dao: com.temenos.microservice.framework.core.outbox.OutboxDaoImpl
      temn.msf.ingest.outbox.cache.namespace: paymentorder-outbox
      tmn.ignite.host: cache-service
      tmn.ignite.port: 10800
      