apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentorder-db
  namespace: payments
spec:
  selector:
    matchLabels:
      name: paymentorder-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: paymentorder-db
    spec:
      containers:
      - image: paymentsacrrepo.azurecr.io/ms-paymentorder-mysql:DEV
        env:
          # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          value: password
        imagePullPolicy: IfNotPresent
        name: paymentorder-db
        ports:
        - containerPort: 3306
      imagePullSecrets:
      - name: paymentsregcredentials
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: paymentorder-db-service
  name: paymentorder-db-service
  namespace: payments
spec:
  type: NodePort
  ports:
  - name: "3306"
    port: 3306
    nodePort: 30010
  selector:
    name: paymentorder-db