apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "paymentorder.name" . }}{{ "-scheduler" }}
  namespace: {{ .Values.namespace }}
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: {{ include "paymentorder.name" . }}{{ "-scheduler" }}
            image: "{{ .Values.image.paymentorderscheduler.repository }}:{{ .Values.image.paymentorderscheduler.tag | default .Chart.AppVersion }}"
            imagePullPolicy: "{{ .Values.image.paymentorderscheduler.pullPolicy }}"
            env:
              - name: DATABASE_KEY
                value: {{ .Values.env.paymentorderscheduler.DATABASE_KEY }} 
              - name: MONGODB_DBNAME
                value: {{ .Values.env.paymentorderscheduler.MONGODB_DBNAME }} 
              - name: MONGODB_CONNECTIONSTR
                value: {{ .Values.env.paymentorderscheduler.MONGODB_CONNECTIONSTR }} 
              - name: temn.msf.name
                value: {{ .Values.env.paymentorderscheduler.temn_msf_name }} 
              - name: temn.msf.security.authz.enabled
                value: {{ .Values.env.paymentorderscheduler.temn_msf_security_authz_enabled | quote }}             
              - name: className_paymentscheduler
                value: {{ .Values.env.paymentorderscheduler.className_paymentscheduler }} 
              - name: className_nosqlInboxCatchup
                value: {{ .Values.env.paymentorderscheduler.className_nosqlInboxCatchup }} 
              - name: className_nosqlOutboxCatchup
                value: {{ .Values.env.paymentorderscheduler.className_nosqlOutboxCatchup }}         
              - name: operationId
                value: {{ .Values.env.paymentorderscheduler.operationId }}             
          restartPolicy: OnFailure