apiVersion: sources.knative.dev/v1alpha1
kind: KafkaSource
metadata:
  name: po-kafka-source-avro
spec:
  consumerGroup: po-consumer-group-avro
  bootstrapServers:
  - my-cluster-kafka-bootstrap.kafka:9092 # note the kafka namespace
  topics:
  - payments-avro
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: payments-ingester-avro