apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: payments-ingester-avro
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: dev.local/temenos/ms-paymentorder-ingester:DEV
          ports:
          - name: http1
            containerPort: 8081
          env:
            - name: DATABASE_KEY
              value: sql
            - name: HOST
              value: payments-db-service
            - name: DATABASE_NAME
              value: payments
            - name: DB_USERNAME
              value: root
            - name: DB_PASSWORD
              value: password
            - name: DRIVER_NAME
              value: com.mysql.jdbc.Driver
            - name: DIALECT
              value: org.hibernate.dialect.MySQL5InnoDBDialect
            - name: DB_CONNECTION_URL
              value: jdbc:mysql://paymentorder-db-service:3306/payments
            - name: MAX_POOL_SIZE
              value: "5"
            - name: MIN_POOL_SIZE
              value: "1"
            - name: temn.msf.name
              value: PaymentOrder
            - name: tem.msf.disableInbox
              value: "true"
            - name: temn.msf.security.authz.enabled
              value: "false"
            - name: EXECUTION_ENV
              value: TEST
            - name: temn.msf.ingest.event.ingester
              value: com.temenos.microservice.framework.core.ingester.MicroserviceIngester
            - name: PAYMENT_ORDEREvent
              value: com.temenos.microservice.payments.ingester.PaymentorderIngesterUpdater
            - name: temn.msf.schema.registry.url
              value: "Payment.Order"