#
# *******************************************************************************
# * Copyright © Temenos Headquarters SA 2021. All rights reserved.
# *******************************************************************************
#

ARG CACHE_BASE_IMAGE
FROM ${CACHE_BASE_IMAGE}