apiVersion: v1
kind: Service
metadata:
  name: {{ include "paymentorder.name" . }}{{ "-poapisvc" }}
  namespace: {{.Values.namespace}}
  labels:
    app.kubernetes.io/name: {{ include "paymentorder.name" . }}{{ "-poapisvc" }}
    helm.sh/chart: {{ include "paymentorder.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.paymentorderapi.type }}
  ports:
    - name: http
      port: {{ .Values.service.paymentorderapi.port }}
      protocol: TCP
      targetPort: 8080
  selector:
    app: {{ .Values.apideployment }}
