#Config based Avro Ingester
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "paymentorder.name" . }}{{ "-avro-ingester" }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "paymentorder.name" . }}{{ "-avro-ingester" }}
  template:
    metadata:
      labels:
        app: {{ include "paymentorder.name" . }}{{ "-avro-ingester" }}
    spec:
      containers:
      - name: {{ include "paymentorder.name" . }}{{ "-avro-ingester" }}
        image: "{{ .Values.image.paymentorderingester.repository }}:{{ .Values.image.paymentorderingester.tag | default .Chart.AppVersion }}"
        ports:
        - containerPort: 8092
        envFrom:
          - configMapRef:
              name: {{ include "paymentorder.name" . }}{{ "-avro-ingester-config" }}
---
#Command Ingester
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "paymentorder.name" . }}{{ "-command-ingester" }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "paymentorder.name" . }}{{ "-command-ingester" }}
  template:
    metadata:
      labels:
        app: {{ include "paymentorder.name" . }}{{ "-command-ingester" }}
    spec:
      containers:
      - name: {{ include "paymentorder.name" . }}{{ "-command-ingester" }}
        image: "{{ .Values.image.paymentorderingester.repository }}:{{ .Values.image.paymentorderingester.tag | default .Chart.AppVersion }}"
        ports:
        - containerPort: 8093
        envFrom:
          - configMapRef:
              name: {{ include "paymentorder.name" . }}{{ "-command-ingester-config" }}      
---
#Event Ingester Ingester
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "paymentorder.name" . }}{{ "-event-ingester" }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "paymentorder.name" . }}{{ "-event-ingester" }}
  template:
    metadata:
      labels:
        app: {{ include "paymentorder.name" . }}{{ "-event-ingester" }}
    spec:
      containers:
      - name: {{ include "paymentorder.name" . }}{{ "-event-ingester" }}
        image: "{{ .Values.image.paymentorderingester.repository }}:{{ .Values.image.paymentorderingester.tag | default .Chart.AppVersion }}"
        ports:
        - containerPort: 8094
        envFrom:
          - configMapRef:
              name: {{ include "paymentorder.name" . }}{{ "-event-ingester-config" }}  
---
#Event Delivery
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "paymentorder.name" . }}{{ "-event-delivery" }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "paymentorder.name" . }}{{ "-event-delivery" }}
  template:
    metadata:
      labels:
        app: {{ include "paymentorder.name" . }}{{ "-event-delivery" }}
    spec:
      containers:
      - name: {{ include "paymentorder.name" . }}{{ "-event-delivery" }}
        image: "{{ .Values.image.paymentorderinboxoutbox.repository }}:{{ .Values.image.paymentorderinboxoutbox.tag | default .Chart.AppVersion }}"
        ports:
        - containerPort: 8095
        envFrom:
          - configMapRef:
              name: {{ include "paymentorder.name" . }}{{ "-eventdelivery-config" }}  
---