#
# *******************************************************************************
# * Copyright © Temenos Headquarters SA 2021. All rights reserved.
# *******************************************************************************
#

apiVersion: v1
kind: Secret
metadata:
  name: clientsecret
  namespace: payments
type: Opaque
data:
  CLIENT_SECRET: ZTM4YjM4ZmUtNGUzZi00ZGU3LTg2NWEtZjM3NDlkMDY4YWIz