apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: payments-scheduler
  namespace: payments
spec:
  template:
    spec:
      containers:
        - image: dev.local/temenos/ms-paymentorder-ingester:DEV
          ports:
          - name: http1
            containerPort: 8080
          envFrom:
            - configMapRef:
                name: payments-scheduler-config