apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: paymentsorder-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: paymentsorderapi.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: payments-order-api-svc-np
            port:
              number: 8080  