apiVersion: sources.knative.dev/v1alpha1
kind: KafkaSource
metadata:
  name: po-avro
  namespace: paymentorder
spec:
  consumerGroup: po-avro-consumer-group
  bootstrapServers:
  - my-cluster-kafka-bootstrap.kafka:9092 # note the kafka namespace
  topics:
  - table-update
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: paymentorder-avro-ingester
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: paymentorder-avro-ingester
  namespace: paymentorder
spec:
  template:
    spec:
      containers:
        - image: dev.local/temenos/ms-paymentorder-ingester:DEV
          ports:
          - name: http1
            containerPort: 8080
          env:
            - name: DATABASE_KEY
              value: mongodb
            - name: MONGODB_CONNECTIONSTR
              value: mongodb://mongodb-0.mongodb-svc.mongodb.svc.cluster.local:27017,mongodb-1.mongodb-svc.mongodb.svc.cluster.local:27017,mongodb-2.mongodb-svc.mongodb.svc.cluster.local:27017
            - name: MONGODB_DBNAME
              value: ms_paymentorder
            - name: temn.msf.name
              value: PaymentOrder  
            - name: PDP_CONFIG
              value: classpath:xacml/payments-pdp-config.xml
            - name: temn.msf.pdp.resource.type
              value: API
            - name: temn.msf.pdp.resource.manager
              value: PAYMENT
            - name: tem.msf.disableInbox
              value: "true"
            - name: temn.msf.security.authz.enabled
              value: "false"
            - name: class.inbox.dao
              value: com.temenos.microservice.framework.core.inbox.InboxDaoImpl
            - name: class.outbox.dao
              value: com.temenos.microservice.framework.core.outbox.OutboxDaoImpl
            - name: EXECUTION_ENV
              value: TEST
            - name: temn.msf.ingest.event.ingester
              value: com.temenos.microservice.framework.core.ingester.MicroserviceIngester
            - name: PAYMENT_ORDEREvent
              value: com.temenos.microservice.paymentorder.ingester.PaymentorderIngesterUpdater
            - name: temn.msf.schema.registry.url
              value: "Payment.Order"