#
# *******************************************************************************
# * Copyright © Temenos Headquarters SA 2021. All rights reserved.
# *******************************************************************************
#

#-------------------------------------------------------------
#- Docker compose base definition file to run containers.
#-----------------------------------------------------------

version: '3.6'
services:      
  api:
    build:
      context: ../../../${API_CONTEXT}
      dockerfile: Dockerfile
      args:
        API_BASE_IMAGE: ${API_BASE_IMAGE}
        api_artifactid: ${api_artifactid}
        api_java_options: ${java_options}
    image: ${API_IMAGE}
  ingester:
    build:
      context: ../../../${INGESTER_CONTEXT}
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: ${INGESTER_APP_BASE_IMAGE}
        artifactid: ${ingester_artifactid}
        java_options: ${java_options} ${REMOTE_DEBUG} ${ingester_jacoco_jvm_opts}
    image: ${INGESTER_IMAGE}
  inboxoutbox:
    build:
      context: ../../../${INBOXOUTBOX_CONTEXT}
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: ${INBOXOUTBOX_BASE_IMAGE}
        artifactid: ${inboxoutbox_artifactid}
        java_options: ${java_options} ${REMOTE_DEBUG}
    image: ${INBOXOUTBOX_IMAGE}
  fileingester:
    build:
      context: ../${FILEINGESTER_CONTEXT}
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: ${FILEINGESTER_BASE_IMAGE}
        artifactid: ${fileingester_artifactid}
        java_options: ${java_options} ${REMOTE_DEBUG} ${ingester_jacoco_jvm_opts}
    image: ${FILEINGESTER_IMAGE}
    volumes:
      - '/usr/local/tomcat/temp'
      - '/usr/local/tomcat'
  scheduler:
    build:
      context: ../${SCHEDULER_CONTEXT}
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: ${SCHEDULER_BASE_IMAGE}
        artifactid: ${scheduler_artifactid}
        java_options: ${java_options} ${REMOTE_DEBUG}
    image: ${SCHEDULER_IMAGE}   