#
# *******************************************************************************
# * Copyright © Temenos Headquarters SA 2021. All rights reserved.
# *******************************************************************************
#

apiVersion: v1
kind: Secret
metadata:
  name: appinitsecret
type: Opaque
data:
  USER_NAME: cm9vdA==
  PASSWORD: cGFzc3dvcmQ=