#-------------------------------------------------------------
#- Docker compose base definition file to run containers.
#-----------------------------------------------------------
---
version: '3.6'
services:
  db-service:
    build:
      context: ${DB_CONTEXT}
      dockerfile: Dockerfile
      args:
        DB_BASE_IMAGE: ${DB_BASE_IMAGE}
    image: ${DB_IMAGE}
    shm_size: '1gb'
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: payments
  
  api:
    build:
      context: ${API_CONTEXT}
      dockerfile: Dockerfile
      args:
        API_BASE_IMAGE: ${API_BASE_IMAGE}
        api_artifactid: ${api_artifactid}
        api_java_options: ${java_options}
    image: ${API_IMAGE}
    
  ingester:
    build:
      context: ${INGESTER_CONTEXT}
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: ${API_BASE_IMAGE}
        artifactid: ${api_artifactid}
        java_options: ${java_options}
    image: ${INGESTER_IMAGE}