#
# *******************************************************************************
# * Copyright © Temenos Headquarters SA 2021. All rights reserved.
# *******************************************************************************
#

apiVersion: v1
kind: Secret
metadata:
  name: posqldbsecret
  namespace: payments
type: Opaque
data:
  USER_NAME: c3lzdGVt
  PASSWORD: T3JhY2xlXzE=