apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "dbinit.name" . }}{{ "-app-init" }}
  labels:
    app.kubernetes.io/name: {{ include "dbinit.name" . }}{{ "-app-init" }}
    helm.sh/chart: {{ include "dbinit.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}  
spec:
  template:
    metadata:
      name: {{ include "dbinit.name" . }}{{ "-app-init" }}
    spec:
   {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
      - name: {{ .Values.imagePullSecrets }} 
    {{- end }}    
      containers:
      - name: {{ include "dbinit.name" . }}{{ "-app-init" }}
        image: "{{ .Values.image.appinit.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}" 
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        env: 
          - name: database.key
            value: {{ .Values.env.appinit.databaseKey }} 
          - name: database.name
            value: {{ .Values.env.appinit.databaseName }} 
          - name: db.connection.url
            value: {{ .Values.env.appinit.dbConnectionUrl }} 
          - name: db.username
            value: {{ .Values.env.appinit.dbUserName }} 
          - name: db.password
            value: {{ .Values.env.appinit.dbPassword }}
          - name: db.auto.upgrade
            value: {{ .Values.env.appinit.dbautoupgrade | quote }}    
          - name: temn.msf.logger.exportType
            value: {{ .Values.env.appinit.exportType }} 
          - name: temn.msf.logger.socketHost
            value: {{ .Values.env.appinit.socketHost | quote }} 
          - name: temn.msf.logger.socketPort
            value: {{ .Values.env.appinit.socketPort | quote }}             
      restartPolicy: {{ .Values.restartPolicy }} 