apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: payments-scheduler
  namespace: payments
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: payments-scheduler
            image: temenos/ms-paymentorder-scheduler:DEV
            imagePullPolicy: Never
            env:
              - name: DATABASE_KEY
                value: sql
              - name: HOST
                value: payments-db-service
              - name: DB_USERNAME
                value: root
              - name: DB_PASSWORD
                value: password               
              - name: DATABASE_NAME
                value: payments
              - name: DRIVER_NAME
                value: com.mysql.jdbc.Driver
              - name: DIALECT
                value: org.hibernate.dialect.MySQL5InnoDBDialect
              - name: DB_CONNECTION_URL
                value: jdbc:mysql://paymentorder-db-service:3306/payments    
              - name: MAX_POOL_SIZE
                value: "5"
              - name: MIN_POOL_SIZE
                value: "1"                   
              - name: temn.msf.name
                value: PaymentOrder
              - name: temn.msf.security.authz.enabled
                value: "false"             
              - name: className_paymentscheduler
                value: com.temenos.microservice.payments.scheduler.PaymentOrderScheduler 
              - name: className_sqlInboxCatchup
                value: com.temenos.microservice.framework.scheduler.core.SqlInboxCatchupProcessor
              - name: className_sqlOutboxCatchup
                value: com.temenos.microservice.framework.scheduler.core.SqlOutboxCatchupProcessor          
              - name: operationId
                value: paymentscheduler            
          restartPolicy: OnFailure
          
          