#Config based Avro Ingester
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "paymentorder.name" . }}{{ "-avro-ingester" }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicacount.paymentorderingester }}
  selector:
    matchLabels:
      app: {{ include "paymentorder.name" . }}{{ "-avro-ingester" }}
  template:
    metadata:
      labels:
        app: {{ include "paymentorder.name" . }}{{ "-avro-ingester" }}
    spec:
      containers:
      - name: {{ include "paymentorder.name" . }}{{ "-avro-ingester" }}
        image: "{{ .Values.image.paymentorderingester.repository }}:{{ .Values.image.paymentorderingester.tag | default .Chart.AppVersion }}"
        ports:
        - containerPort: 8092
        envFrom:
          - configMapRef:
              name: {{ include "paymentorder.name" . }}{{ "-ingester-avro-config" }}
---
#Command Ingester
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "paymentorder.name" . }}{{ "-command-ingester" }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicacount.paymentorderingester }}
  selector:
    matchLabels:
      app: {{ include "paymentorder.name" . }}{{ "-command-ingester" }}
  template:
    metadata:
      labels:
        app: {{ include "paymentorder.name" . }}{{ "-command-ingester" }}
    spec:
      containers:
      - name: {{ include "paymentorder.name" . }}{{ "-command-ingester" }}
        image: "{{ .Values.image.paymentorderingester.repository }}:{{ .Values.image.paymentorderingester.tag | default .Chart.AppVersion }}"
        ports:
        - containerPort: 8093
        envFrom:
          - configMapRef:
              name: {{ include "paymentorder.name" . }}{{ "-ingester-command-config" }}      
---
#Event Ingester Ingester
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "paymentorder.name" . }}{{ "-event-ingester" }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicacount.paymentorderingester }}
  selector:
    matchLabels:
      app: {{ include "paymentorder.name" . }}{{ "-event-ingester" }}
  template:
    metadata:
      labels:
        app: {{ include "paymentorder.name" . }}{{ "-event-ingester" }}
    spec:
      containers:
      - name: {{ include "paymentorder.name" . }}{{ "-event-ingester" }}
        image: "{{ .Values.image.paymentorderingester.repository }}:{{ .Values.image.paymentorderingester.tag | default .Chart.AppVersion }}"
        ports:
        - containerPort: 8094
        envFrom:
          - configMapRef:
              name: {{ include "paymentorder.name" . }}{{ "-ingester-event-config" }}  
---
#Event Delivery
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "paymentorder.name" . }}{{ "-event-delivery" }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicacount.paymentorderingester }}
  selector:
    matchLabels:
      app: {{ include "paymentorder.name" . }}{{ "-event-delivery" }}
  template:
    metadata:
      labels:
        app: {{ include "paymentorder.name" . }}{{ "-event-delivery" }}
    spec:
      containers:
      - name: {{ include "paymentorder.name" . }}{{ "-event-delivery" }}
        image: "{{ .Values.image.paymentorderinboxoutbox.repository }}:{{ .Values.image.paymentorderinboxoutbox.tag | default .Chart.AppVersion }}"
        ports:
        - containerPort: 8095
        envFrom:
          - configMapRef:
              name: {{ include "paymentorder.name" . }}{{ "-eventdelivery-config" }}  
---
#Data Ingester
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "paymentorder.name" . }}{{ "-data-ingester" }}
  namespace: {{.Values.namespace}}
spec:
  replicas: {{ .Values.replicacount.paymentorderingester }}
  selector:
    matchLabels:
      app: {{ include "paymentorder.name" . }}{{ "-data-ingester" }}
  template:
    metadata:
      labels:
        app: {{ include "paymentorder.name" . }}{{ "-data-ingester" }}
    spec:
      containers:
      - name: {{ include "paymentorder.name" . }}{{ "-data-ingester" }}
        image: "{{ .Values.image.paymentorderingester.repository }}:{{ .Values.image.paymentorderingester.tag | default .Chart.AppVersion }}"
        ports:
        - containerPort: 8080
        envFrom:
          - configMapRef:
              name: {{ include "paymentorder.name" . }}{{ "-ingester-data-config" }}    
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentorder-file-ingester
  namespace: {{.Values.namespace}}
spec:
  replicas: {{ .Values.replicacount.paymentorderingester }}
  selector:
    matchLabels:
      app: paymentorder-file-ingester
  template:
    metadata:
      labels:
        app: paymentorder-file-ingester
    spec:
      volumes:
      - name: filestorage
        hostPath:
          path: /var/lib/fileingesterstorage
          type: DirectoryOrCreate
      - name: fileprocessed
        hostPath:
          path: /var/lib
          type: DirectoryOrCreate
      containers:
      - name: paymentorder-file-ingester
        image: {{ .Values.image.fileingester.repository }}:{{ .Values.image.fileingester.tag }}
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /var/lib/fileingesterstorage
          name: filestorage
        - mountPath: /var/lib
          name: fileprocessed
        envFrom:
          - configMapRef:
              name: paymentorder-ingester-file-config
        env:
          # Use secret in real usage
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: ponosqldbsecret
                key: USER_NAME 
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ponosqldbsecret
                key: PASSWORD                   
---
#Data Ingester Service
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: {{ include "paymentorder.name" . }}{{ "-data-ingester-svc" }}
  name: {{ include "paymentorder.name" . }}{{ "-data-ingester-svc" }}
  namespace: {{.Values.namespace}}
spec:
  selector:
    app: {{ include "paymentorder.name" . }}{{ "-data-ingester" }}
  ports:
    - name: http
      protocol: TCP
      port: 8080
      nodePort: 30007
  type: NodePort    
---
#Command Ingester Service
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: {{ include "paymentorder.name" . }}{{ "-command-ingester-svc" }}
  name: {{ include "paymentorder.name" . }}{{ "-command-ingester-svc" }}
  namespace: {{.Values.namespace}}
spec:
  selector:
    app: {{ include "paymentorder.name" . }}{{ "-command-ingester" }}
  ports:
    - name: http
      protocol: TCP
      port: 8080
      nodePort: 30008
  type: NodePort  
---
#Data Ingester Service Jacoco
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: {{ include "paymentorder.name" . }}{{ "-data-ingester-svc-jacoco" }}
  name: {{ include "paymentorder.name" . }}{{ "-data-ingester-svc-jacoco" }}
  namespace: {{.Values.namespace}}
spec:
  selector:
    app: {{ include "paymentorder.name" . }}{{ "-data-ingester" }}
  ports:
    - name: http
      protocol: TCP
      port: 36330
      nodePort: 30330
  type: NodePort    
---
#Avro Ingester Service Jacoco
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: {{ include "paymentorder.name" . }}{{ "-avro-ingester-svc-jacoco" }}
  name: {{ include "paymentorder.name" . }}{{ "-avro-ingester-svc-jacoco" }}
  namespace: {{.Values.namespace}}
spec:
  selector:
    app: {{ include "paymentorder.name" . }}{{ "-avro-ingester" }}
  ports:
    - name: http
      protocol: TCP
      port: 36330
      nodePort: 30331
  type: NodePort    
---
#Event Ingester Service Jacoco
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: {{ include "paymentorder.name" . }}{{ "-event-ingester-svc-jacoco" }}
  name: {{ include "paymentorder.name" . }}{{ "-event-ingester-svc-jacoco" }}
  namespace: {{.Values.namespace}}
spec:
  selector:
    app: {{ include "paymentorder.name" . }}{{ "-event-ingester" }}
  ports:
    - name: http
      protocol: TCP
      port: 36330
      nodePort: 30336
  type: NodePort    
---
#Command Ingester Service Jacoco
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: {{ include "paymentorder.name" . }}{{ "-command-ingester-svc-jacoco" }}
  name: {{ include "paymentorder.name" . }}{{ "-command-ingester-svc-jacoco" }}
  namespace: {{.Values.namespace}}
spec:
  selector:
    app: {{ include "paymentorder.name" . }}{{ "-command-ingester" }}
  ports:
    - name: http
      protocol: TCP
      port: 36330
      nodePort: 30334
  type: NodePort 
---
#File Ingester Service Jacoco
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: {{ include "paymentorder.name" . }}{{ "-file-ingester-svc-jacoco" }}
  name: {{ include "paymentorder.name" . }}{{ "-file-ingester-svc-jacoco" }}
  namespace: {{.Values.namespace}}
spec:
  selector:
    app: {{ include "paymentorder.name" . }}{{ "-file-ingester" }}
  ports:
    - name: http
      protocol: TCP
      port: 36330
      nodePort: 30337
  type: NodePort   