kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ include "paymentorder.name" . }}{{ "-api" }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "paymentorder.name" . }}{{ "-api" }}
    helm.sh/chart: {{ include "paymentorder.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.paymentorderapiReplicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "paymentorderapi.selectorLabels" . | nindent 6 }}
      app: paymentorder-api
  template:
    metadata:
      labels:
        {{- include "paymentorderapi.selectorLabels" . | nindent 8 }}
        app: paymentorder-api
    spec:
    {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
      - name: {{ .Values.imagePullSecrets }} 
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}{{ "-api" }}
          image: "{{ .Values.image.paymentorderapi.repository }}:{{ .Values.image.paymentorderapi.tag | default .Chart.AppVersion }}"
          ports:
            - containerPort: 80
              protocol: TCP
          securityContext:
            privileged: true
          env:
            - name: DATABASE_KEY
              value: {{ .Values.env.paymentorderapi.DATABASE_KEY }} 
            - name: MONGODB_DBNAME
              value: {{ .Values.env.paymentorderapi.MONGODB_DBNAME }}
            - name: MONGODB_CONNECTIONSTR
              value: {{ .Values.env.paymentorderapi.MONGODB_CONNECTIONSTR }}
            - name: className_CreateNewPaymentOrders
              value: {{ .Values.env.paymentorderapi.className_CreateNewPaymentOrders }}
            - name: className_CreateNewPaymentOrder
              value: {{ .Values.env.paymentorderapi.className_CreateNewPaymentOrder }} 
            - name: className_GetPaymentOrders
              value: {{ .Values.env.paymentorderapi.className_GetPaymentOrders }}
            - name: className_UpdatePaymentOrder
              value: {{ .Values.env.paymentorderapi.className_UpdatePaymentOrder }} 
            - name: className_GetPaymentOrder
              value: {{ .Values.env.paymentorderapi.className_GetPaymentOrder }} 
            - name: className_GetPaymentOrderCurrency
              value: {{ .Values.env.paymentorderapi.className_GetPaymentOrderCurrency }} 
            - name: className_getHealthCheck
              value: {{ .Values.env.paymentorderapi.className_getHealthCheck }}
            - name: API_HEALTH_CHECK_BUSINESS_CONDITION
              value: {{ .Values.env.paymentorderapi.API_HEALTH_CHECK_BUSINESS_CONDITION }}
            - name: className_UpdateNewPaymentOrders
              value: {{ .Values.env.paymentorderapi.className_UpdateNewPaymentOrders }}
            - name: className_DeletePaymentOrders
              value: {{ .Values.env.paymentorderapi.className_DeletePaymentOrders }}
            - name: className_FileUpload
              value: {{ .Values.env.paymentorderapi.className_FileUpload }}
            - name: className_createReferenceData
              value: {{ .Values.env.paymentorderapi.className_createReferenceData }} 
            - name: className_getReferenceData
              value: {{ .Values.env.paymentorderapi.className_getReferenceData }}
            - name: className_updateReferenceData
              value: {{ .Values.env.paymentorderapi.className_updateReferenceData }}
            - name: className_addReferenceData
              value: {{ .Values.env.paymentorderapi.className_addReferenceData }}
            - name: className_deleteReferenceData
              value: {{ .Values.env.paymentorderapi.className_deleteReferenceData }}
            - name: className_UpdateStatus
              value: {{ .Values.env.paymentorderapi.className_UpdateStatus }}  
            - name: className_DeleteWithCondition
              value: {{ .Values.env.paymentorderapi.className_DeleteWithCondition }}  
            - name: className_FileDownload
              value: {{ .Values.env.paymentorderapi.className_FileDownload }}
            - name: className_DoInputValidation
              value: {{ .Values.env.paymentorderapi.className_DoInputValidation }} 
            - name: className_GetInputValidation
              value: {{ .Values.env.paymentorderapi.className_GetInputValidation }}
            - name: className_deletePaymentOrder
              value: {{ .Values.env.paymentorderapi.className_deletePaymentOrder }}
            - name: className_CreateEmployee
              value: {{ .Values.env.paymentorderapi.className_CreateEmployee }}
            - name: className_GetEmployee
              value: {{ .Values.env.paymentorderapi.className_GetEmployee }}
            - name: className_UpdateEmployee
              value: {{ .Values.env.paymentorderapi.className_UpdateEmployee }}    
            - name: className_DeleteEmployee
              value: {{ .Values.env.paymentorderapi.className_DeleteEmployee }}      
            - name: className_CreateUser
              value: {{ .Values.env.paymentorderapi.className_CreateUser }}
            - name: className_GetUser
              value: {{ .Values.env.paymentorderapi.className_GetUser }}
            - name: className_searchUsers
              value: {{ .Values.env.paymentorderapi.className_searchUsers }}    
            - name: className_createCustomer
              value: {{ .Values.env.paymentorderapi.className_createCustomer }} 
            - name: className_getCustomers
              value: {{ .Values.env.paymentorderapi.className_getCustomers }}
            - name: className_CreateAccount
              value: {{ .Values.env.paymentorderapi.className_CreateAccount }}
            - name: className_GetAccount
              value: {{ .Values.env.paymentorderapi.className_GetAccount }}    
            - name: className_DeleteAccount
              value: {{ .Values.env.paymentorderapi.className_DeleteAccount }}   
            - name: className_UpdateAccount
              value: {{ .Values.env.paymentorderapi.className_UpdateAccount }} 
            - name: className_FileDelete
              value: {{ .Values.env.paymentorderapi.className_FileDelete }}   
            - name: className_GetAccountValidate
              value: {{ .Values.env.paymentorderapi.className_GetAccountValidate }}   
            - name: temn.msf.name
              value: {{ .Values.env.paymentorderapi.temn_msf_name }} 
            - name: temn.msf.pdp.resource.type
              value: {{ .Values.env.paymentorderapi.temn_msf_pdp_resource_type }}   
            - name: temn.msf.pdp.resource.manager
              value: {{ .Values.env.paymentorderapi.temn_msf_pdp_resource_manager }} 
            - name: temn.msf.stream.vendor
              value: {{ .Values.env.paymentorderapi.temn_msf_stream_vendor }} 
            - name: temn.queue.impl
              value: {{ .Values.env.paymentorderapi.temn_queue_impl }}  
            - name: temn.msf.stream.kafka.bootstrap.servers
              value: {{ .Values.env.paymentorderapi.temn_msf_stream_kafka_bootstrap_servers }} 
            - name: PDP_CONFIG
              value: {{ .Values.env.paymentorderapi.PDP_CONFIG }}   
            - name: IRIS_PROTOCOL
              value: {{ .Values.env.paymentorderapi.IRIS_PROTOCOL | quote }}   
            - name: IRIS_HOST_IP
              value: {{ .Values.env.paymentorderapi.IRIS_HOST_IP | quote }} 
            - name: IRIS_PORT
              value: {{ .Values.env.paymentorderapi.IRIS_PORT | quote }}   
            - name: IRIS_PATH
              value: {{ .Values.env.paymentorderapi.IRIS_PATH | quote }} 
            - name: IRIS_R18_PATH
              value: {{ .Values.env.paymentorderapi.IRIS_R18_PATH | quote }} 
            - name: IRIS_VERSION
              value: {{ .Values.env.paymentorderapi.IRIS_VERSION | quote }}  
            - name: temn.msf.storage.home
              value: {{ .Values.env.paymentorderapi.temn_msf_storage_home | quote }}   
            - name: FILE_STORAGE_URL
              value: {{ .Values.env.paymentorderapi.FILE_STORAGE_URL }}   
            - name: temn.msf.max.file.upload.size
              value: {{ .Values.env.paymentorderapi.temn_msf_max_file_upload_size | quote }} 
            - name: ms.security.tokencheck.enabled
              value: {{ .Values.env.paymentorderapi.ms_security_tokencheck_enabled | quote }}   
            - name: temn.entitlement.stubbed.service.enabled
              value: {{ .Values.env.paymentorderapi.temn_entitlement_stubbed_service_enabled | quote }} 
            - name: JWT_TOKEN_ISSUER
              value: {{ .Values.env.paymentorderapi.JWT_TOKEN_ISSUER }} 
            - name: JWT_TOKEN_PRINCIPAL_CLAIM
              value: {{ .Values.env.paymentorderapi.JWT_TOKEN_PRINCIPAL_CLAIM | quote }}
            - name: ID_TOKEN_SIGNED
              value: {{ .Values.env.paymentorderapi.ID_TOKEN_SIGNED | quote }} 
            - name: JWT_TOKEN_PUBLIC_KEY
              value: {{ .Values.env.paymentorderapi.JWT_TOKEN_PUBLIC_KEY | quote }} 