#
# *******************************************************************************
# * Copyright © Temenos Headquarters SA 2021. All rights reserved.
# *******************************************************************************
#

# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
# #
# apiVersion: v1
# kind: Service
# metadata:
  # # annotations:
    # # meta.helm.sh/release-name: cp-helm-charts
    # # meta.helm.sh/release-namespace: default
  # creationTimestamp: "2020-12-22T07:26:01Z"
  # labels:
    # app: cp-schema-registry
    # # app.kubernetes.io/managed-by: Helm
    # # chart: cp-schema-registry-0.1.0
    # # heritage: Helm
    # # release: cp-helm-charts
  # name: cp-helm-charts-cp-schema-registry-svc
  # namespace: default
  # # resourceVersion: "24214"
  # # selfLink: /api/v1/namespaces/default/services/cp-helm-charts-cp-schema-registry
  # # uid: bc592888-5da2-4efa-9c38-ba7e8ff3fbba
# spec:
  # #clusterIP: 10.0.224.182
  # ports:
  # - name: schema-registry
    # port: 8081
    # protocol: TCP
    # targetPort: 8081
  # - name: metrics
    # port: 5556
    # protocol: TCP
    # targetPort: 5556
  # selector:
    # app: cp-schema-registry
    # release: cp-helm-charts
  # sessionAffinity: None
  # type: LoadBalancer
# status:
  # loadBalancer: {}
  
  
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: schema-registry-lb
  name: schema-registry-lb
  namespace: default
spec:
  selector:
    app: cp-schema-registry
  ports:
    - name: http
      protocol: TCP
      port: 8081
      targetPort: 8081
  type: LoadBalancer   
