#
# *******************************************************************************
# * Copyright © Temenos Headquarters SA 2021. All rights reserved.
# *******************************************************************************
#

ARG JAEGER_BASE_IMAGE
FROM ${JAEGER_BASE_IMAGE}
