apiVersion: sources.knative.dev/v1alpha1
kind: KafkaSource
metadata:
  name: po-kafka-source-avro
  namespace: payments
spec:
  consumerGroup: po-consumer-group-avro
  bootstrapServers:
  - my-cluster-kafka-bootstrap.kafka:9092 # note the kafka namespace
  topics:
  - table-update-paymentorder
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: payments-ingester-avro
---
apiVersion: sources.knative.dev/v1alpha1
kind: KafkaSource
metadata:
  name: po-kafka-source-eventdelivery
  namespace: payments
spec:
  consumerGroup: po-consumer-group-eventdelivery
  bootstrapServers:
  - my-cluster-kafka-bootstrap.kafka:9092 # note the kafka namespace
  topics:
  - paymentorder-outbox
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: payments-ingester-eventdelivery
---
apiVersion: sources.knative.dev/v1alpha1
kind: KafkaSource
metadata:
  name: po-kafka-source-eventingester
  namespace: payments
spec:
  consumerGroup: po-consumer-group-eventingester
  bootstrapServers:
  - my-cluster-kafka-bootstrap.kafka:9092 # note the kafka namespace
  topics:
  - paymentorder-event-topic
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: payments-ingester-eventingester
---
apiVersion: sources.knative.dev/v1alpha1
kind: KafkaSource
metadata:
  name: po-kafka-source-command
  namespace: payments
spec:
  consumerGroup: po-consumer-group-command
  bootstrapServers:
  - my-cluster-kafka-bootstrap.kafka:9092 # note the kafka namespace
  topics:
  - ms-paymentorder-inbox-topic
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: payments-ingester-command
---
apiVersion: sources.knative.dev/v1alpha1
kind: KafkaSource
metadata:
  name: po-kafka-source-data
  namespace: payments
spec:
  consumerGroup: po-consumer-group-data
  bootstrapServers:
  - my-cluster-kafka-bootstrap.kafka:9092 # note the kafka namespace
  topics:
  - table-update
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: payments-ingester-data