#
# *******************************************************************************
# * Copyright © Temenos Headquarters SA 2021. All rights reserved.
# *******************************************************************************
#

apiVersion: v1
kind: Secret
metadata:
  name: posqldbsecret
  namespace: postgresql
type: Opaque
data:
  POSTGRES_USER: cGF5bWVudG9yZGVydXNy
  POSTGRES_PASSWORD: cGF5bWVudG9yZGVycGFzcw==