#
# *******************************************************************************
# * Copyright © Temenos Headquarters SA 2021. All rights reserved.
# *******************************************************************************
#

apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentorder-db-postgres
  namespace: postgresql
spec:
  selector:
    matchLabels:
      name: paymentorder-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: paymentorder-db
    spec:
      containers:
        - name: paymentorder-db
          image: ms-paymentorder-postgres
          env:
            - name: POSTGRES_DB
              value: paymentorderdb
          # Use secret in real usage
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: posqldbsecret
                  key: POSTGRES_PASSWORD
          # Use secret in real usage
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: posqldbsecret
                  key: POSTGRES_USER            
          imagePullPolicy: IfNotPresent
          name: paymentorder-db
          ports:
          - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: po-postgresqldb-service
  namespace: postgresql
spec:
  type: NodePort
  ports:
   - port: 5432
     targetPort : 5432
     nodePort: 30010
  selector:
    name: paymentorder-db
    