#
# *******************************************************************************
# * Copyright © Temenos Headquarters SA 2021. All rights reserved.
# *******************************************************************************
#

apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentorder-db-postgres
  namespace: postgresql
spec:
  selector:
    matchLabels:
      name: paymentorder-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: paymentorder-db
    spec:
      securityContext:
        # Changes the ownership of the volume mounted folders to postgres user  
        fsGroup: 999         
      volumes:
        - name: config-vol
          configMap:
            name: postgresql-config
        - name: secret-cert-vol
          secret:
            secretName: postgresql-cert
        - name: secret-key-vol
          secret:
            secretName: postgresql-key
            # To restrict the access of private key files only to postgres group users
            defaultMode: 0600
      containers:
        - name: paymentorder-db
          image: ms-paymentorder-postgres
          env:
            - name: POSTGRES_DB
              value: paymentorderdb
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: posqldbsecret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: posqldbsecret
                  key: POSTGRES_USER            
          imagePullPolicy: IfNotPresent
          args:
            - -c
            - ssl=on
            - -c
            - hba_file=/etc/postgresql-config-vol/pg_hba.conf         
            - -c
            - ssl_cert_file=/etc/postgresql-cert-secrets-vol/server.crt
            - -c
            - ssl_key_file=/etc/postgresql-key-secrets-vol/server.key
          name: paymentorder-db
          ports:
          - containerPort: 5432
          volumeMounts:
          - name: config-vol
            mountPath: /etc/postgresql-config-vol
          - name: secret-cert-vol
            mountPath: /etc/postgresql-cert-secrets-vol
          - name: secret-key-vol
            mountPath: /etc/postgresql-key-secrets-vol      
---
apiVersion: v1
kind: Service
metadata:
  name: po-postgresqldb-service
  namespace: postgresql
spec:
  type: NodePort
  ports:
   - port: 5432
     targetPort : 5432
     nodePort: 30010
  selector:
    name: paymentorder-db
    