#
# *******************************************************************************
# * Copyright © Temenos Headquarters SA 2021. All rights reserved.
# *******************************************************************************
#

apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentorder-db
  namespace: payments
spec:
  selector:
    matchLabels:
      name: paymentorder-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: paymentorder-db
    spec:
      imagePullSecrets:
      - name: paymentorderregcredentials
      containers:
      - image: paymentorderacr.azurecr.io/ms-paymentorder-mysql:latest
        env:
          # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: posqldbsecret
              key: PASSWORD
        imagePullPolicy: IfNotPresent
        name: paymentorder-db
        ports:
        - containerPort: 3306

