#
# *******************************************************************************
# * Copyright © Temenos Headquarters SA 2021. All rights reserved.
# *******************************************************************************
#

apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: paymentorder-db-service
  name: paymentorder-db-service
  namespace: payments
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 3007
      targetPort: 3306  
  selector:
    name: paymentorder-db