#
# *******************************************************************************
# * Copyright © Temenos Headquarters SA 2021. All rights reserved.
# *******************************************************************************
#

apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: paymentorder-scheduler
  namespace: paymentorder
spec:
  template:
    spec:
      containers:
        - image: dev.local/temenos/ms-paymentorder-ingester:DEV
          ports:
          - name: http1
            containerPort: 8080
          envFrom:
            - configMapRef:
                name: paymentorder-scheduler-config
            - configMapRef:
                name: paymentorder-mongo-db-config    