#
# *******************************************************************************
# * Copyright © Temenos Headquarters SA 2021. All rights reserved.
# *******************************************************************************
#

# Default values for dbInitialisation.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  sqlinit:
    repository: 
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: DEV

# Set the pull secret name here
#imagePullSecrets: all-icr-io

restartPolicy: OnFailure

env:
  dbcred: "N"
  sqlinit:
    ##MySQL
    databaseKey: sql
    databaseName: 
    dbdialect: org.hibernate.dialect.MySQL5InnoDBDialect
    dbusername: root
    dbpassword: password
    dbconnectionurl: 
    dbdriver:
    dbautoupgrade: "N"
    exportType: socket
    socketHost: 
    socketPort: 4560     
    
    ##MSSQL
    # databaseKey: sql
    # databaseName: metering
    # dbdialect: org.hibernate.dialect.SQLServer2012Dialect
    # dbusername: sa
    # dbpassword: Rootroot@12345
    # dbconnectionurl: jdbc:sqlserver://metering-db-service.metering.svc.cluster.local:1433
    # msversion: DEV.0.0-SNAPSHOT   
    # dbdriver: com.microsoft.sqlserver.jdbc.SQLServerDriver     
    # migration: path:database/install/     

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

