#
# *******************************************************************************
# * Copyright © Temenos Headquarters SA 2021. All rights reserved.
# *******************************************************************************
#

apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "appinit.name" . }}{{ "-sql-init" }}
  labels:
    app.kubernetes.io/name: {{ include "appinit.name" . }}{{ "-sql-init" }}
    helm.sh/chart: {{ include "appinit.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}  
spec:
  template:
    metadata:
      name: {{ include "appinit.name" . }}{{ "-sql-init" }}
    spec:
   {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
      - name: {{ .Values.imagePullSecrets }} 
    {{- end }}    
      containers:
      - name: {{ include "appinit.name" . }}{{ "-sql-init" }}
        image: "{{ .Values.image.sqlinit.repository }}" 
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        env: 
          - name: database.key
            value: {{ .Values.env.sqlinit.databaseKey }}
          - name: database.name
            value: {{ .Values.env.sqlinit.databaseName }}
          - name: db.driver.name
            value: {{ .Values.env.sqlinit.dbdriver }}
          - name: db.dialect
            value: {{ .Values.env.sqlinit.dbdialect }}
          - name: db.connection.url
            value: {{ .Values.env.sqlinit.dbconnectionurl }}    
          - name: db.auto.upgrade
            value: {{ .Values.env.sqlinit.dbautoupgrade | quote }} 
          - name: temn.msf.logger.exportType
            value: {{ .Values.env.sqlinit.exportType }} 
          - name: temn.msf.logger.socketHost
            value: {{ .Values.env.sqlinit.socketHost | quote }} 
          - name: temn.msf.logger.socketPort
            value: {{ .Values.env.sqlinit.socketPort | quote }}  
        {{- if eq .Values.env.dbcred "Y" }}
          - name: db.username
            valueFrom:
              secretKeyRef:
                name: appinitsecret
                key: USER_NAME 
          - name: db.password
            valueFrom:
              secretKeyRef:
                name: appinitsecret
                key: PASSWORD
        {{ else }}
          - name: db.username
            value: {{ .Values.env.sqlinit.dbusername }}
          - name: db.password
            value: {{ .Values.env.sqlinit.dbpassword }}
        {{- end }}
      restartPolicy: {{ .Values.restartPolicy }}             